package.json, yarn.lock
`react-error-boundary` should not get added as both a peer and dev dependency.
=> (chore) Fix dependency issue

src/utils/common-expression-helpers.ts, src/utils/expression-runner.ts
Added calculate gravida helper function
=> O3-2059 Add calculate gravida helper function

src/components/inputs/date/ohri-date.component.tsx, src/components/inputs/multi-select/ohri-multi-select.component.tsx, src/components/inputs/number/ohri-number.component.tsx, src/components/inputs/radio/ohri-radio.component.tsx, src/components/inputs/select/ohri-dropdown.component.tsx, src/components/inputs/text-area/ohri-text-area.component.tsx, src/components/inputs/text/ohri-text.component.tsx
Fix typo that caused regressions with rendering validation errors
=> Fix highlighting of field validation errors

src/components/inputs/content-switcher/ohri-content-switcher.component.tsx, src/components/inputs/date/ohri-date.component.tsx, src/components/inputs/multi-select/ohri-multi-select.component.tsx, src/components/inputs/number/ohri-number.component.tsx, src/components/inputs/radio/ohri-radio.component.tsx, src/components/inputs/select/ohri-dropdown.component.tsx, src/components/inputs/text-area/ohri-text-area.component.tsx, src/components/inputs/text/ohri-text.component.tsx, src/components/inputs/toggle/ohri-toggle.component.tsx
Fixes broken rendering of fields whose `type` isn't supported
=> Fix rendering for fields with undefined handlers

README.md
=> (docs) Updated instructions for local development

__mocks__/forms/omrs-forms/mini-form.json, __mocks__/forms/omrs-forms/nested-form1.json, src/api/api.ts, src/components/encounter/ohri-encounter-form.tsx, src/hooks/useFormJson.test.tsx, src/hooks/useFormJson.tsx, src/utils/common-expression-helpers.ts
- Add a couple of improvements to ensure sub-forms loads correctly. I have disabled some tests that are failing am intending on fixing them, just want to get your feedback @samuelmale @denniskigen @pirupius 
```json
{
"name": "Mini sub form",
"pages": [
{
"isSubform": "true",
"subform": {
"name": "Mini form A"
}
},
{
"label": "Mini sub form",
"sections": [
{
"label": "Mini sub form",
"isExpanded": "true",
"questions": [
{
"label": "Pulse",
"type": "obs",
"required": true,
"id": "miniSubPulse",
"rendering": "number",
"concept": "5087AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"conceptMappings": [
{
"relationship": "SAME-AS",
"type": "CIEL",
"value": "5087"
},
{
"relationship": "SAME-AS",
"type": "AMPATH",
"value": "5087"
},
{
"relationship": "NARROWER-THAN",
"type": "LOINC", …
```
=> (enhc) add improvement on loading sub-forms

src/components/page/ohri-form-page.tsx
- This PR filters out empty Sections from Form pages. Empty Sections are sections that are either Hidden on the form page or sections that have no questions or whose questions are all Hidden.
- There is some code improvements as well to the code filtering out sections
=> Filters out Empty/Hidden Sections in a Page

package.json, src/components/encounter/ohri-encounter-form.tsx, src/utils/common-expression-helpers.ts, src/utils/expression-runner.ts
=> Apply linter

src/components/inputs/fixed-value/ohri-fixed-value.component.tsx, src/components/inputs/text/ohri-text.component.tsx, src/components/repeat/ohri-repeat.component.tsx, src/hooks/useFormsConfig.tsx
So we only use what we need and take advantage of tree shaking.
=> (chore) Import lodash functions from the ES module

src/validators/ohri-form-validator.ts
=> Remove un-used import

.github/workflows/ci.yml
This PR, creates a Bot that fetches all 3 esms latest branch, builds, updates YARN lock 
with pre-release of Form-engine, and creates a PR to each repo.
=> Configure Actions to pull next pre-release, create 3 PRs to 3 REPOS

.github/workflows/ci.yml
=> (chore) Fix indentantion error on YAML, after bump job

src/hooks/usePatientData.tsx, src/ohri-form.component.tsx
=> (feat) Add age in patient object

src/api/types.ts, src/components/repeat/ohri-repeat.component.tsx
=> (feat) Limit obs-group repeat

package.json, src/components/inputs/date/ohri-date.component.tsx, src/components/repeat/ohri-repeat.component.tsx, src/ohri-form.component.test.tsx, src/submission-handlers/base-handlers.ts, src/utils/common-expression-helpers.ts, src/utils/ohri-form-helper.ts, src/validators/default-value-validator.test.ts, src/validators/default-value-validator.ts, src/validators/ohri-form-validator.ts, src/validators/ohri-js-expression-validator.test.ts, yarn.lock
Moves date handling concerns from the `moment` library to `dayjs`.
=> (chore) Use `dayjs` for handling dates

package.json, src/utils/common-expression-helpers.ts, yarn.lock
Removes a reference to `moment` that ought to have been removed in #44.
=> (fix) Remove all references to `moment`

src/utils/common-expression-helpers.ts
- Updated calcTimeDiff to use dayjs
=> (refactor) Updated calcTimeDiff to use dayjs

src/ohri-form.component.tsx, src/utils/error-utils.ts, src/validators/ohri-form-validator.ts
This PR addresses two key improvements:
1. Enhanced Failed Submission Reporting: To provide a better user experience, we have improved the way failed submissions are reported by displaying the precise error message explaining why the submission has failed. This allows users to quickly identify the issue and make the necessary corrections to their submission.
2. Fixed Number Field Validation Issue: We discovered an issue where, for number fields, the max and min validators were being triggered even when the field value was undefined. This has now been resolved, ensuring that the validators are only activated when a value is present in the number field.
=> (enhc) Enhance failed submission reporting and fix number field validation issue

src/api/types.ts, src/components/encounter/ohri-encounter-form.component.tsx, src/components/repeat/ohri-repeat.component.tsx
=> feat: limit obs repeat based on business logic

src/components/inputs/date/ohri-date.scss
=> (fix): Enhance date-time component spacing and show time format am/pm

src/components/encounter/ohri-encounter-form.component.tsx, src/components/page/ohri-form-page.tsx, src/ohri-form.component.tsx
Pickup and apply "isExpanded" property from the form section as defined in the schema
=> Pickup and apply "section.isExpanded"

README.md
=> (docs) Move pbcopy to right place in example

src/index.ts
Exposes forms-loader functions to be available to esms depending on the library.
=> Expose useFormJson to be useable out of the library

src/components/encounter/ohri-encounter-form.component.tsx
Fixes a regression where subforms stopped rendering
=> (fix) Minor fix enabling subforms to render correctly

src/hooks/useFormJson.tsx
This PR ensures that the form UUID in the JSON Schema is accurately configured.
N/A
=> Sync Form UUID in Form Schema with Form JSON

src/components/encounter/ohri-encounter-form.component.tsx
=> OHRI-1389 Evaluate Calculate expressions on hidden fields

package.json, src/components/repeat/ohri-repeat.component.tsx, src/components/repeat/ohri-repeat.test.ts, yarn.lock
This PR resolves the issue where skip logic doesn't work as expected within repeated obs groups
=> Generated obs-group field ID should be a valid JS identifier

.github/workflows/ci.yml
The current pipeline fails on on the OHRI repo, due to:
1. Lack of form-engine dependency on working branch
2. Wrong branch to bump the form-engine
=> Update base branch from working to dev

src/components/encounter/ohri-encounter-form.component.tsx
=> fix subform loading

src/components/encounter/ohri-encounter-form.component.tsx
Added patient object to the expresion runner context object
=> Added patient object to the expresion runner context object

src/api/types.ts, src/hooks/usePostSubmissionAction.tsx, src/ohri-form.component.tsx
This PR basically introduces the ability to pass an arbitrary config object to post actions making it possible to reuse these handlers.
NB: These changes are backward compatible 
N/A
=> Ability to configure post submission actions

src/components/repeat/helpers.ts, src/components/repeat/ohri-repeat.component.tsx, src/hooks/useInitialValues.ts, src/index.ts, src/submission-handlers/base-handlers.test.ts, src/submission-handlers/base-handlers.ts, src/utils/common-utils.ts
This is a cleanup post https://github.com/openmrs/openmrs-form-engine-lib/pull/101. It basically ensures that we use the standard handler to initialize repeated fields.
=> (chore) Use standard handler to initialise repeated fields

src/hooks/useInitialValues.test.ts, src/ohri-form.component.test.tsx, src/utils/common-expression-helpers.ts
Mostly this relates to local time being only slightly > UTC## Requirements
Builds on top of #110 to add "real" typings for the common-expression-helpers. Since these are invoked dynamically, it's not a huge amount of help, but hopefully makes things clearer for anyone simply reading this file.
=> (chore) Better typings for common-expression-helpers

src/components/encounter/ohri-encounter-form.component.tsx, src/components/group/ohri-obs-group.component.tsx, src/components/inputs/content-switcher/ohri-content-switcher.test.tsx, src/components/inputs/select/ohri-dropdown.test.tsx, src/components/inputs/ui-select-extended/ui-select-extended.tsx, src/components/inputs/unspecified/ohri-unspecified.test.tsx, src/components/repeat/ohri-repeat.component.tsx, src/components/section/helpers.ts, src/components/section/ohri-form-section.component.tsx, src/hooks/useFormFieldHandlers.tsx, src/hooks/useFormFieldValidators.ts, src/hooks/useInitialValues.test.ts, src/hooks/useInitialValues.ts, src/hooks/usePostSubmissionAction.tsx, src/ohri-form-context.tsx, src/registry/inbuilt-components/inbuiltControls.ts, src/registry/inbuilt-components/inbuiltDataSources.ts, src/registry/inbuilt-components/inbuiltFieldSubmissionHandlers.ts, src/registry/inbuilt-components/inbuiltValidators.ts, src/registry/registry.test.ts, src/registry/registry.ts, src/utils/expression-runner.test.ts, src/utils/expression-runner.ts, yarn.lock
Introduces the ability to register custom functions to be used as expression helpers. It also revamps the registry system to rely on the global store defined by the framework.
N/A
=> (feat) Add support for registering custom helper functions

src/utils/expression-runner.ts
=> Add registered expression helpers to the expression context

__mocks__/forms/ohri-forms/test-enrolment-form.json, src/api/types.ts, src/components/encounter/ohri-encounter-form.component.tsx, src/ohri-form.component.test.tsx
=> O3-2253: Ability to mark a form field as transient

src/components/encounter/ohri-encounter-form.component.tsx
Ability to edit L&D form enabled
https://github.com/openmrs/openmrs-form-engine-lib/assets/19629227/42a11688-98a8-4aac-bf22-f69a4be6d31a
=> OHRI-1897:Ability to edit L&D form enabled

src/components/encounter/ohri-encounter-form.component.tsx, src/ohri-form.component.tsx
This card is linked to --> [https://ohri.atlassian.net/browse/OHRI-1850]
=> (fix ) Ensure a fixed value field is submitted when nested in obsGroup 

src/api/api.ts
=> OHRI-1923 fix undefined length property error

src/submission-handlers/base-handlers.ts
=> fix date error on form edit

src/components/inputs/number/ohri-number.component.tsx
=> (fix) Fixing jumping cursor issue on the number component.

src/components/inputs/number/ohri-number.component.tsx
Reverts openmrs/openmrs-form-engine-lib#142
Previous PR has some breaking changes and needs further changes
=> Revert "(fix) Fixing jumping cursor issue on the number component."

src/submission-handlers/base-handlers.ts
[OHRI-2005](https://ohri.atlassian.net/jira/software/projects/OHRI/boards/1?assignee=640074db9cba7ca02877c179&selectedIssue=OHRI-2005)
Fix "error rendering field"
https://github.com/openmrs/openmrs-form-engine-lib/assets/19629227/538b4c24-5e28-407c-a60f-e6d82f406e84
=> OHRI-2005:Fix "error rendering field"

src/api/types.ts, src/components/encounter/ohri-encounter-form.component.tsx, src/components/inputs/unspecified/ohri-unspecified.component.tsx
https://github.com/openmrs/openmrs-form-engine-lib/assets/51090527/02e0f42d-49d7-4d83-8ad2-68a7ee3392c3
=> (fix)Fixes jumping cursor issue

src/validators/ohri-date-validator.ts
Remove "t.getTime" error on the ANC form in ohri-namibia working and ohri-working
https://github.com/openmrs/openmrs-form-engine-lib/assets/130601439/83d9b268-1549-4a25-9149-bac90724d5fa
=> OHRI-2021 :Remove "t.getTime" error on the ANC form in ohri-namibia working

package.json, src/api/types.ts, yarn.lock
This is a minor fix that was causing yarn link to fail because of conflicting dependencies with react error boundary
N/A
N/A
=> (chore) fix link issue with react error boundary

src/registry/registry.ts
The PR fixes an issue that was created after adding inbuilt post submission actions. The engine would pick the inbuilt post submission actions but not the custom ones.
=> fix getRegisteredPostSubmissionAction function to handle both custom and inbuilt post submission actions correctly

.github/workflows/ci.yml
This PR aims to resolve the deprecation issue with this action
=> (chore) bump peter-evans/create-pull-request version

package.json, src/components/inputs/select/ohri-dropdown.test.tsx, src/declarations.d.tsx, src/ohri-form.component.test.tsx, src/ohri-form.component.tsx, src/utils/test-utils.ts, tsconfig.json, yarn.lock
Changes in this PR basically do the following:
1. Bumps Carbon version from `v1.13.0` to `v.1.37.0`
2. Bumps ESM Framework version
3. Fix husky hooks
4. Use Snack bar
5.  Align deps
6. Fix tests
N/A
N/A
N/A
=> (chore) Bump Carbon version

src/constants.ts, src/datasources/concept-data-source.ts
Fix missing forward slash in drugs endpoint, caused when adding a new openmrs rest base url
=> (fix) Fix missing forward slash in concepts endpoint

package.json, src/components/group/ohri-obs-group.component.tsx, src/components/inputs/content-switcher/ohri-content-switcher.component.tsx, src/components/inputs/date/ohri-date.component.tsx, src/components/inputs/file/file.component.tsx, src/components/inputs/file/file.scss, src/components/inputs/location/ohri-encounter-location.component.tsx, src/components/inputs/multi-select/ohri-multi-select.component.tsx, src/components/inputs/number/ohri-number.component.tsx, src/components/inputs/radio/ohri-radio.component.tsx, src/components/inputs/select/ohri-dropdown.component.tsx, src/components/inputs/text-area/ohri-text-area.component.tsx, src/components/inputs/text/ohri-text.component.tsx, src/components/inputs/ui-select-extended/ui-select-extended.component.tsx, src/components/sidebar/ohri-form-sidebar.component.tsx, src/components/value/view/ohri-field-value-view.component.tsx, src/components/value/view/ohri-field-value-view.scss, src/ohri-form.component.tsx, yarn.lock
This PR integrates the [classnames](https://www.npmjs.com/package/classnames) library to clean up and simplify rendering conditional logic determining which styles to use.
=> (refactor) Clean up conditional styling logic using classnames

src/components/inputs/workspace-launcher/workspace-launcher.component.tsx
This attempts to fix a TS error encountered when bumping the form-engine version.
=> (fix) Remove relative path from an import statement

src/form-engine.test.tsx, src/utils/test-utils.ts, src/zscore-tests/bmi-age.test.tsx, src/zscore-tests/height-age.test.tsx, src/zscore-tests/weight-height.test.tsx
This PR addresses flaky tests, likely caused by concurrency issues (resulting from multiple running threads or processes). @denniskigen's approach of waiting for the loader works, but with the RFE, we may need to rectify unnecessary re-renders and manage loading dependencies through a single loading state.
=> (test) Fix intermittently failing tests

src/components/section/helpers.ts, src/post-submission-actions/program-enrollment-action.ts
Fixed regression on program enrollments and error handling
https://github.com/openmrs/openmrs-form-engine-lib/assets/19533785/1a66d709-37a0-4b70-8ecb-11a1d7fd46b7
=> (fix) Fixed error messages on saving program enrollments

yarn.lock
Bumps the core tooling to the latest pre-release versions.
=> (chore) Bump openmrs and @openmrs/esm-framework

README.md
- Add documentation for translations, orders and markdown
=> (docs) Add documentation for translations, orders and markdown

src/submission-handlers/base-handlers.ts
This pr ensures that if either `result` or `datatype` is null or undefined, the code doesn't throw an error.
=> Fix: Use optional chaining helps catch unexpected errors

src/components/encounter/encounter-form.component.tsx, src/form-engine.component.tsx, translations/en.json, translations/es.json, translations/fr.json, translations/km.json
PR  fixes encounter updated or created snackbar message, 
https://github.com/openmrs/openmrs-form-engine-lib/assets/53287480/eebc9590-6d97-4408-b44c-0c33e9602b09
[O3-3160](https://openmrs.atlassian.net/browse/O3-3160)
[O3-3160]: https://openmrs.atlassian.net/browse/O3-3160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> (fix) O3-3160: Fix encounter updated snackbar message

__mocks__/forms/rfe-forms/conditional-required-form.json, __mocks__/forms/rfe-forms/required-form.json, src/components/encounter/encounter-form.component.tsx, src/components/inputs/date/date.component.tsx, src/components/inputs/multi-select/multi-select.component.tsx, src/components/inputs/number/number.component.tsx, src/components/inputs/radio/radio.component.tsx, src/components/inputs/radio/radio.scss, src/components/inputs/select/dropdown.component.tsx, src/components/inputs/text-area/text-area.component.tsx, src/components/inputs/text/text.component.tsx, src/components/inputs/text/text.test.tsx, src/components/inputs/ui-select-extended/ui-select-extended.component.tsx, src/components/inputs/unspecified/unspecified.component.tsx, src/form-engine.test.tsx, src/types.ts, src/utils/boolean-utils.ts, src/utils/form-helper.ts, src/validators/date-validator.test.ts, src/validators/date-validator.ts, src/validators/default-value-validator.test.ts, src/validators/form-validator.test.ts, src/validators/form-validator.ts
https://github.com/openmrs/openmrs-form-engine-lib/assets/47450907/b52eaf47-dc2e-4979-830e-cd937933af92
https://openmrs.atlassian.net/browse/O3-3058
=> O3-3058: Support for Conditional Required Validation

package.json, yarn.lock
This PR cuts a new major release. It also bumps the versions of core tooling used to the latest `next` tagged releases.
=> (chore) Release v2.0.0

src/submission-handlers/patientIdentifierHandler.ts, src/submission-handlers/patietnIdentifierHandler.test.ts
Test suits to cover the patient identifier handler on handling value submission and also getting initial values of the form
=> (test) Add tests for the patient identifier handler 

src/api/api.ts, src/constants.ts
- Currently we are using a full representation of the encounter resource post encounter submission, this pr attempts to load only the necessary data
https://openmrs.atlassian.net/browse/O3-3166
=> (fix) O3-3166 Use a custom encounter representation post encounter submission

src/components/encounter/encounter-form.component.tsx
This fixes an error in the form-builder where the patient object in the form context is always undefined.
=> (fix) Fix error caused by referencing an undefined patient object

src/submission-handlers/patientIdentifierHandler.ts, src/submission-handlers/programStateHandler.ts, src/transformers/angular-fe-schema-transformer.ts
This PR addresses issues identified during a work session with the METS team, these include:
- Program states were not being initialised with a previous value which caused a minor bug with the "fixed-value" rendering
- The AFE supports capturing encounter dates configured with the ui-select-extended rendering
- Nested orders not rendering answer options correctly
- The patient identifier control breaks within the form-builder
=> (fix) Miscellaneous fixes

src/components/encounter/encounter-form-manager.ts
This PR expands the filter for file attachment logic and removes fields of rendering `file` that have no submission value.
=> (fix) follow-up fix for file attachment logic

src/constants.ts, src/registry/inbuilt-components/inbuiltFieldSubmissionHandlers.ts, src/submission-handlers/obsCommentHandler.ts, src/transformers/angular-fe-schema-transformer.ts, src/types.ts
- Capture obs comments if user adds `showComments` true
https://www.loom.com/share/afe8ff2306b8478fb17f30514381bb3f?sid=3bb53ebd-8336-4f5a-b573-5a4fdded013e
=> O3-3161 Capture obs comments

src/components/encounter/encounter-form-manager.test.ts, src/components/encounter/encounter-form-manager.ts
This PR ensures that we avoid duplicating program enrollments in scenarios where we capture multiple workflow states of the same program.
https://openmrs.atlassian.net/browse/O3-3315
=> (fix) Group patient states by Program

__mocks__/forms/afe-forms/test-schema-transformer-form.json, src/components/encounter/encounter-form.component.tsx, src/components/inputs/number/number.component.tsx, src/components/inputs/text-area/text-area.component.tsx, src/components/inputs/text/text.component.tsx, src/hooks/useFieldValidationResults.ts, src/hooks/useFormFieldValidators.ts, src/registry/inbuilt-components/inbuiltTransformers.ts, src/registry/inbuilt-components/inbuiltValidators.ts, src/transformers/default-schema-transformer.test.ts, src/transformers/default-schema-transformer.ts, src/utils/form-helper.ts, src/validators/default-value-validator.test.ts, src/validators/default-value-validator.ts
This aims at fixing the issue where field validation wasn't happening as expected on "value change"
https://openmrs.atlassian.net/browse/O3-3208
=> (fix) Ensure form fields are initialised with all base validators

src/components/encounter/encounter-form.component.tsx, src/components/errors/error-modal.component.tsx, src/components/errors/error.scss, src/components/inputs/date/date.component.tsx, src/form-engine.component.tsx
Follow up ticket to https://github.com/openmrs/openmrs-form-engine-lib/pull/200
=> O3-3058: Add the inline notification

src/utils/common-expression-helpers.ts
This PR resolves the issue with failing `calcGravida` expression.
=> (fix) fix for failing calcGravida expression

src/components/inputs/date/date.component.tsx, src/form-engine.test.tsx, yarn.lock
This PR introduces the `OpenmrsDatepicker` component from openmcore/esm-styleguide. Since the Ethiopian team already uses this component in patient registration, there's no need for them to register a different datepicker in Form Engine.
https://github.com/openmrs/openmrs-form-engine-lib/assets/12844964/017df011-ca0e-4d4e-967e-27a304687c51
=> (feat) Introduce locale/Openmrs datepicker

src/components/inputs/radio/radio.component.tsx, src/types.ts
… 
This PR enable setting radio buttons horizontally or vertically 
https://www.loom.com/share/88c8a730b15443e2a74b79348e9af031
https://openmrs.atlassian.net/browse/O3-3389
=> (feat)03-3389: Support Orientation Options for Radio Buttons

yarn.lock
Bumps the version of the core tooling used in this repo. This should fix some of the type errors you see when linking to their the Form Builder or the Patient Chart.
=> (chore) Bump core tooling

src/components/inputs/ui-select-extended/ui-select-extended.component.tsx, src/datasources/concept-data-source.ts
Drug Rendering displays incorrect repeated obs-group lists
https://www.loom.com/share/3ccb56eff08b4aecbeb8d91dcb7b5708?sid=b41da14f-50f3-4466-bc01-ec979d6e3113
https://www.loom.com/share/f4e70bcd833d4459b2f67560aefd3041?sid=6965361a-5567-4756-bdcb-731143ca80de
=> (fix) O3-3379 Drug Rendering displays incorrect repeated obs-group lists

src/utils/expression-parser.test.ts
Adding test coverage for the `extractArgs` and `hasParentheses` functions
=> (test):Adding test coverage for expression parser functions

package.json, yarn.lock
This PR bumps up turbo and the framework.
=> (chore): Bump core and turbo

src/components/inputs/date/date.component.tsx, src/components/inputs/date/date.scss, src/form-engine.test.tsx, yarn.lock
This PR fixes the label in the `OpenmrsDatePicker` so that it no longer breaks into two lines and updates the error message prop as the date picker can now render it by itself.
https://github.com/openmrs/openmrs-esm-core/pull/1062 - must be merged first
=> (fix): Fix styling issues in the OpenmrsDatePicker

package.json, yarn.lock
Bumps version to the next minor release (v2.1.0)
=> (chore) Release v2.1.0

src/components/inputs/radio/radio.component.tsx, src/validators/default-value-validator.ts
When an answer is selected on a radio button field the is no way the user can clear is selection. This pr attempts to address that.
https://github.com/openmrs/openmrs-form-engine-lib/assets/19533785/96d0646f-2d35-4d3f-ae84-f103a4f20f51
=> (feat) O3-3359: Add ability to clear radio button values

src/components/inputs/date/date.component.tsx
This PR adds the missing validation props for the time picker.
=> (chore) Add invalid and warn props to Timepicker

src/processors/encounter/encounter-form-processor.ts, src/provider/form-factory-helper.ts
This PR ensures that hidden or disabled fields aren't subjected to any kind of validation on form submission.
=> https://openmrs.atlassian.net/browse/O3-3874
=> (fix) Hidden and disabled fields shouldn't be validated on form-submission

src/adapters/program-state-adapter.ts, src/processors/encounter/encounter-form-processor.ts
Prepopulate program states field in different forms for questions with the same program
=> (fix) Correctly initialise program state fields

src/components/inputs/number/number.component.tsx
This PR resolves an issue that previously surfaced where the number input component isn't correctly initialised in edit mode.
=> (fix) Resolve binding issue for the number input

src/components/inputs/select/dropdown.component.tsx, src/components/inputs/select/dropdown.test.tsx, src/constants.ts, src/transformers/default-schema-transformer.ts
Adds ability to clear a dropdown selection.
- https://openmrs.atlassian.net/browse/O3-3855
NOTE: This PR simply builds on top of https://github.com/openmrs/openmrs-esm-form-engine-lib/pull/371. It basically offers a simplified approach to the matter; kudos @TrevorAntony
=> (feat) Support for clearing dropdown selection

src/hooks/useInitialValues.test.ts, src/hooks/useInitialValues.ts
This PR sdds test coverage for the useInitialValues hook
https://openmrs.atlassian.net/browse/O3-3943
=> (tests) O3-3943: Add test coverage for the useInitialValues hook

src/adapters/obs-adapter.ts, src/types/index.ts, src/types/schema.ts, src/utils/common-utils.test.ts, src/utils/common-utils.ts, src/utils/form-helper.test.ts, src/utils/form-helper.ts
=> (chore) Fix cyclic refs in the encounter form processor

src/components/inputs/multi-select/multi-select.component.tsx
=> (Fix) O3-3881 - Resolve tooltip not being displayed for the Multicheckbox question

__mocks__/forms/rfe-forms/radio-button-form.json, src/components/inputs/radio/radio.component.tsx, src/components/inputs/radio/radio.test.tsx, src/components/label/label.component.tsx
O3-3930 Add test coverage for the RadioInput component
=> (tests) O3-3930 Add test coverage for the RadioInput component

src/components/inputs/text/text.test.tsx
O3-3932 Enable TextInput component test suite
=> O3-3932 Enable TextInput component test suite

src/components/inputs/number/number.test.tsx
Add test coverage for the NumberField component
https://github.com/user-attachments/assets/602c33f7-8184-451f-b620-75ef2d269d1f
=> (chore) Add test coverage for the NumberField component

src/adapters/obs-adapter.test.ts, src/components/inputs/text/text.test.tsx
Adds test coverage for the obs adapter 
https://openmrs.atlassian.net/browse/O3-3923
=> (chore) Add unit tests for the obs adapter

src/adapters/program-state-adapter.test.ts
-Add test coverage for the ProgramStateAdapter
=> (test) O3-3925 Add test coverage for the ProgramStateAdapter

__mocks__/forms/rfe-forms/hide-pages-and-sections-form.json, src/components/renderer/field/fieldLogic.ts, src/form-engine.test.tsx, src/hooks/useEvaluateFormFieldExpressions.ts, src/hooks/useFormStateHelpers.ts, src/utils/common-utils.ts
Fixes the ability of hiding sections and pages based on the form state
- https://openmrs.atlassian.net/browse/O3-3905
=> (fix) Enable Hiding of Sections and Pages

src/processors/encounter/encounter-processor-helper.ts
Remove unnecessary obs group transformation since the hierarchy is already properly constructed in `processObsGroup`.
https://openmrs.atlassian.net/browse/O3-4137
=> (fix)O3-4137: Remove redundant obs group transformation

README.md
Updates the README with more context about what the Form Engine is, and how to use it.
=> (docs) Update README

package.json, yarn.lock
- Bumps `esm-framework`
- Adds `esm-style-guide` as a dev dependency
=> (chore) Bump `esm-framework`

yarn.lock
Bumps esm framework for patch release
=> (chore) Bump esm-framework version

package.json
This PR cuts a minor release for the latest changes including the following changes:
* (fix) O3-3881: Render tooltips for optional multi-select fields by @samuelmale in https://github.com/openmrs/openmrs-esm-form-engine-lib/pull/460
* (chore) Transifex migration for translations to @openmrs/esm-form-engine-app by @pirupius in https://github.com/openmrs/openmrs-esm-form-engine-lib/pull/457
* (fix) O3-4410: Adjust Form Workspace Size & Enhance Form UI by @vasharma05 in https://github.com/openmrs/openmrs-esm-form-engine-lib/pull/461
None
None
=> (chore) Release v3.1.1

package.json
=> (chore) Patch Release v3.1.2

.eslintrc, package.json, src/adapters/encounter-diagnosis-adapter.ts, src/hooks/useFormFieldValueAdapters.ts, src/processors/form-processor.ts, yarn.lock
Adds the ESLint import plugin and configures it to prevent duplicate imports. Also fixes duplicate import violations in the codebase.
=> (chore) Add eslint-plugin-import to prevent duplicate imports

README.md
Adds a new section to the README that helps developers resolve common dependency version mismatches when using `yarn link`, specifically focusing on `@carbon/react` conflicts. Includes example error messages and resolution steps using the package.json `resolutions` field.
=> (docs) Add troubleshooting steps for linking issues

package.json
=> (chore) Patch release v3.1.3

src/form-engine.component.tsx
=> (feat) Adding data prop to onSumbit to allow passing saved info to other dependent components

package.json
Cuts a patch release of React Form Engine with backwards-compatible refactors, bug fixes, and housekeeping changes:
* (refactor) Reorganize mock data and fix test warnings by @denniskigen in https://github.com/openmrs/openmrs-esm-form-engine-lib/pull/486
* (fix) Add data prop to onSumbit to allow passing saved info to other dependent components by @ynurmahomed in https://github.com/openmrs/openmrs-esm-form-engine-lib/pull/485
* (fix) Make the whole label as tooltip trigger by @vasharma05 in https://github.com/openmrs/openmrs-esm-form-engine-lib/pull/475
* (fix) Fix undefined `min` and `max` values for number inputs by @vasharma05 in https://github.com/openmrs/openmrs-esm-form-engine-lib/pull/492
* (chore) Add auto-update for OpenMRS dependencies by @ibacher in …
=> (chore) Release v3.1.4

jest.config.js, package.json, src/components/error/error-modal.component.tsx, src/components/field-label/field-label.component.tsx, src/components/inputs/multi-select/multi-select.component.tsx, src/components/inputs/radio/radio.component.tsx, src/components/inputs/text/text.component.tsx, src/components/label/label.component.tsx, src/declarations.d.ts, src/types/schema.ts, tsconfig.json, yarn.lock
This PR effects a host of changes to get this app in alignment with Core following [this change](https://github.com/openmrs/openmrs-esm-core/pull/1346). Presently, both [tests and the build script](https://github.com/openmrs/openmrs-esm-template-app/actions/workflows/update-openmrs-deps.yml) are failing. These changes include:
- Bumping the `openmrs` and `@openmrs/esm-framework` libraries to the latest versions to get us in alignment with Core.
- Bumping `@carbon/react`, `webpack` and `webpack-cli` to align with the versions in Core.
- Amending the `transform` and `transformIgnorePatterns` configuration properties in the Jest config to ensure that ES modules in the `@openmrs` package (and other necessary dependencies) are properly transformed before being executed by Jest.
- Fixing some …
=> (chore) O3-4745: Fix failing dependency auto-update CI workflow

src/components/inputs/date/date.scss, src/components/inputs/unspecified/unspecified.component.tsx, src/components/inputs/unspecified/unspecified.test.tsx, src/components/renderer/field/form-field-renderer.component.tsx, src/form-engine.test.tsx, src/provider/form-factory-helper.ts
Fixes a couple of issues related to form validation and UI fixes, which include:
1. Subjecting validation to unspecified fields while in edit mode
2. Stale validation errors showing up on interacting with an unspecified field
3. Date picker's width stretches out with very long labels
https://github.com/user-attachments/assets/df120b17-6c2c-44ca-b581-72ba4663d7ec
Date picker UX:
https://github.com/user-attachments/assets/56177b1a-0c66-48c3-84d0-5c1058f64466
=> (fix) Various fixes related to form validation

package.json, yarn.lock
The purpose of this PR is to Bump @openmrs/esm-framework peer dep from 6.x to 7.x
=> (chore) Bump @openmrs/esm-framework peer dep from 6.x to 7.x

src/components/sidebar/sidebar.scss, src/form-engine.scss
shrinked the size of the sidebar down from it’s current width (12rem) to 11.25rem and remove the right margin. 
Commented out the width, it shall be relevant with a future ticket about the workspace width
@ibacher , @denniskigen  review this pr
https://openmrs.atlassian.net/issues/?filter=-1&selectedIssue=O3-4515
=> (fix) O3-4515 Form workspace redesign
