openmrs/openmrs-esm-form-engine-lib

- LICENSE.txt
- README.md
This React Form Engine, now called the "OpenMRS Form Engine", previously-called the OHRI Form Engine, had an MIT license and UCSF (c). Today, with support from UCSF team members, we have worked together (OMRS and UCSF) to move the source repo into the OpenMRS community. I would like to follow our conventions and change this to MPL v2 with Healthcare Disclaimer to follow community conventions so this can be safely re-used and co-maintained by our global OpenMRS community.
> Updating License from MIT to MPL v2 w HCD, without Copyright

- src/components/encounter/ohri-encounter-form.tsx
- src/hooks/useEncounterRole.tsx
At the moment the `hard` code value for encounterRole is `Clinician` for some implementors this might be missing. I have added the ability to retrieve the `encounterRole` and add preference to `Clinician` as the default value if present. In its absence the `UnKnown` encounterRole is picked.
@denniskigen @samuelmale @pirupius @larslemos What are your thoughts on this approach.
> (feat) Add ability to retrieve encounter type and default to `unknown` encounter role

- src/api/types.ts
Adds an optional `version` property to the OHRIFormSchema interface. This should allow a user building a schema using the O3 Form Builder to be able to specify a version number directly in their JSON schema.
> (feat) Add optional version property to OHRIFormSchema interface

- src/components/group/ohri-obs-group.component.tsx
- src/components/repeat/ohri-repeat.component.tsx
Add null checks for `ohri-obs-group` and `ohri-repeat` components to avoid them failing if an undefined question is wired in the form.
> (fix) fix failing obs-group and repeat component due to `undefined` bug

- package.json
Adds a `TIMING=1` variable to the lint step, essentially ensuring we have some output from linting that can be [cached](https://turbo.build/repo/docs/core-concepts/caching#configuring-cache-outputs).
> (chore) Cacheable ESLint output

- package.json
- src/components/encounter/ohri-encounter-form.tsx
- src/hooks/useWorkspaceLayout.ts
- src/ohri-form.component.test.tsx
- src/ohri-form.component.tsx
- src/ohri-form.scss
- yarn.lock
This PR refactors the implementation of useWorkspaceLayout to better support arbitrary workspaces and ensure better form responsiveness. The updated implementation eliminates the funkiness present in the current version. Additionally, the "react-error-boundary" library has been added as a shared dependency, as it is being used by multiple MFs.
OHRI Form render workspace:
Patient Chart workspace:
Known issues:
1. If you were observant enough with the patient chart demo, whenever the container breakpoint is reached (< 1000), the banner disappears and the primary controls get to the bottom, when we decrease the viewport by a few more pixels the sidebar drops to the bottom creating more room for the container hence it switches back to "maximized" mode. When we further shrink the viewport the …
> (fix) Refactor `useWorkspaceLayout` hook to properly support arbitrary workspaces

- src/components/inputs/radio/ohri-radio.component.tsx
- src/ohri-form.scss
- Fix overlapping radio and checkbox text (Updated the input width to match the container width)
> O3-2016 Fix overlapping radio and checkbox text

- .github/workflows/size.yml
- package.json
Adds a CI workflow that evaluates bundle size changes per commit. This PR also adds an `analyze` script to the manifest file that developers can run to view a graphical overview of the bundle that this app exports.
> (chore) Add a CI workflow that tracks bundle sizes changes

- src/components/inputs/number/ohri-number.component.tsx
Number input values have been incrementing and decrementing when in focus and a mouse is scrolled. 
https://user-images.githubusercontent.com/15266028/232490071-24b5dcea-bec9-435b-a4e1-95a8a2e5ed3e.mov
[](https://issues.openmrs.org/browse/O3-2050)
> O3-2050 prevent number input change on mouse/touchpad scroll

- src/api/api.ts
- src/components/encounter/ohri-encounter-form.tsx
- src/components/inputs/date/ohri-date.component.tsx
- src/components/sidebar/ohri-form-sidebar.component.tsx
- src/ohri-form.component.tsx
- src/submission-handlers/base-handlers.ts
- src/utils/boolean-utils.ts
Adds yet more miscellaneous fixes, including:
- Renaming the default label for the `Timepicker` component that gets rendered when the `datetime` rendering type gets used. 
- Ensuring nested properties of `handler` objects can be accessed safely. Ideally, the existence of these properties ought to be determined ahead of time, but this fix carries us over for the time being. 
- Minimal refactors, including renaming a function that determines whether its parameter is a UUID.
> (fix) Yet more miscellaneous fixes

- src/ohri-form.component.tsx
- src/ohri-form.scss
Adds some miscellaneous improvements, including:
- Constraining the height of the `LinearLoader` component when loading a form's dependencies.
- Making the display of the patient banner non-contingent on the availability of a patient UUID. Presently, the form schema will fail to render in some scenarios when a patientUuid is unavailable.
> (fix) Miscellaneous improvements

- src/components/encounter/ohri-encounter-form.tsx
- src/validators/default-value-validator.ts
- src/validators/ohri-form-validator.ts
This PR fixes the issue where there's an error on the number field and field is highlighted in red but no error message is displayed.
> O3-2057 Add support to display error messages on Number input control

- src/ohri-form.scss
> (fix):Fixed position of save/cancel button on form engine

- __mocks__/visit.mock.ts
- src/components/encounter/ohri-encounter-form.tsx
- src/ohri-form.component.test.tsx
- src/ohri-form.component.tsx
… fields
Passed active visit uuid in form if it exists
> O3-2061: Introduce visit as an optional parameter to the form-engine

- src/ohri-form.component.tsx
The form engine attaches a unique timestamp for every observation. It should just have one time-stamp since they are recorded at the same time.
> fixed different timestamps on obs

- src/api/types.ts
- src/validators/ohri-form-validator.test.ts
- src/validators/ohri-form-validator.ts
Both text and number fields have been using `min` and `max` params which caused a little bit of confusion putting into consideration the context. This PR introduces `minLength` and `maxLength` specifically for `field.length` validation.
> Introduce maxLength and minLength params for text fields

- src/components/encounter/ohri-encounter-form.tsx
- src/components/inputs/content-switcher/ohri-content-switcher.component.test.tsx
- src/components/inputs/select/ohri-dropdown.component.test.tsx
- src/components/inputs/unspecified/ohri-unspecified.component.test.tsx
- src/ohri-form-context.tsx
- src/ohri-form.component.tsx
- src/registry/registry.ts
- src/submission-handlers/base-handlers.test.ts
- src/submission-handlers/base-handlers.ts
- src/submission-handlers/encounterDatetimeHandler.ts
This PR adds provision for using the encounter date time type in form JSON. This is mostly important for retrospective data and if an encounter date is passed, it overrides the default(current date)
The JSON implementation is as below:
` {
"label": "Encounter Date:",
"type": "encounterDatetime",
"rendering": "date",
"concept": "163137AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
},
"validators": [
{
"type": "date",
"allowFutureDates": "false"
}
],
"id": "encDate"
}`
> Add provision for Encounter Date Time

- src/components/encounter/ohri-encounter-form.tsx
- src/utils/common-expression-helpers.ts
- src/utils/expression-parser.test.ts
- src/utils/expression-parser.ts
- src/utils/expression-runner.test.ts
- src/utils/expression-runner.ts
This PR streamlines the Expression Runner by removing the necessity for manually registering interdependent fields and incorporating value interpolation within referenced helper functions. Additionally, it revitalizes the support for custom arbitrary data sources within the engine.
https://www.notion.so/ucsf-ighs/Add-custom-data-sources-eg-HTS-ML-a6477780a99a48b09af1990d17ec9695
> Simplify the ExpressionRunner's internal workings and enhance support for custom datasources

- src/components/inputs/text/ohri-text.component.tsx
- src/setupTests.ts
- src/validators/ohri-form-validator.test.ts
- src/validators/ohri-form-validator.ts
This PR fixes an issue with the number and text input validators that caused the validations to fail silently. Ultimately, this issue led to forms failing to POST when saved.
> (fix) Fix validators for number and text inputs

- src/components/page/ohri-form-page.tsx
Fix the issue that was causing repeated sections and the empty sections bug when multiple sections (3 or more) are present.
> (fix) Fix repeating Form Sections issue

- src/utils/forms-loader.ts
This ensures the form sections use the specified hide expressions when behaviours haven't been specified
https://user-images.githubusercontent.com/15266028/234874081-5cf09788-50ad-4aa3-b8e4-2e6a08d1211b.mov
> Default to section hide expression without behaviours

- src/components/encounter/ohri-encounter-form.tsx
- src/validators/ohri-form-validator.test.ts
- src/validators/ohri-form-validator.ts
This is an attempt to fix a bug while submitting a form. This error causes the validation to fail silently without a shouting console error as shown in the picture below. The root cause being that while looping over the error array on the validate function, in  `OHRIFieldValidator` it doesn't return an error for the case of text length validator. This causes the validate function to try loop over an object that isn't an array therefore failing silently making it hard to pick. Hoping this resolves this painful bug.
> (fix) fix bug on submitting a form

- src/components/encounter/ohri-encounter-form.tsx
- src/hooks/usePatientData.tsx
- src/utils/expression-runner.ts
This PR attempts to provide `sex` and `age` to the evaluation context. This is to enable backward compatibility and achieve `schema` parity.
> (enhc) Add ability to provide `age` and `sex` to the evaluation context

- src/utils/expression-runner.ts
This is a follow up PR to fix error where the expression runner was failing because in cases where we are evaluating the field validators the patient object isn't provided, since we are destructuring the patient object we run into an undefined error. This PR fixes that issue with `undefined` values. Secondly is to enhance the error handling by adding the failing expression to the dev-console
> (fix) follow up PR to fix error brought by introducing `age` and `sex` in execution context

- package.json
- yarn.lock
Switches to using the version of `dayjs` provided by the app shell - should solve the problems faced when attempting to link the form engine with the patient chart repo.
> (chore) Use shared `dayjs` version

- src/components/encounter/ohri-encounter-form.tsx
- src/components/page/ohri-form-page.tsx
Adds support for conditionally hiding `pages` if:
- All the `sections` in the `page` definition have `isHidden` set to a "true".
- All the `questions` of all the `sections` in the page have `isHidden` set to "true".
- The page's `isHidden` property is set to "true".
> **Before**: All the questions in the `Examination Details` section are hidden by validation rules, which means the page shouldn't get displayed at all
> **After**: The `Examination Details` section is appropriately hidden
> (feat) Support for conditionally hiding `pages`

- src/ohri-form.component.tsx
Attempt to extract the exact error message from the server response if the encounter POST request fails when submitting a form.
> (feat) Show error message from server when form submission fails

- src/components/inputs/date/ohri-date.scss
- src/components/inputs/radio/ohri-radio.component.tsx
- src/components/inputs/radio/ohri-radio.scss
- src/components/previous-value-review/previous-value-review.component.tsx
- src/components/previous-value-review/previous-value-review.scss
- src/components/value/ohri-value.component.tsx
- src/components/value/ohri-value.scss
This PR fixes the appearance of the previous value review UI after a regression following #68. Specifically, it tweaks the styling of the radio field, ensuring that both it and the review UI get enough breathing room. This PR also cleans up a bit of styling cruft and changes some of the wording of elements in the previous value UI.
> Before
> After
> (fix) Fix previous value review UI

- src/components/inputs/multi-select/ohri-multi-select.scss
- src/components/inputs/number/ohri-number.component.tsx
- src/components/inputs/number/ohri-number.scss
Fixes a broken feature of highlighting the field's label when a field is **required** for number and multiselect controls. In addition to the above, this PR also includes an enhancement that adds support for decimal values to the number input control. Previously, only whole numbers were accepted, but now users can input decimal values as well.
> Fix highlight validation error messages for required field in number and multiselect controls

- src/components/encounter/ohri-encounter-form.component.tsx
- src/components/inputs/content-switcher/ohri-content-switcher.component.tsx
- src/components/inputs/location/ohri-encounter-location.component.tsx
- src/components/previous-value-review/previous-value-review.component.tsx
- src/components/repeat/ohri-repeat.component.tsx
- src/components/section-collapsible-toggle/ohri-section-collapsible-toggle.component.tsx
- src/components/sidebar/ohri-form-sidebar.component.tsx
- src/components/warning-modal.component.tsx
- src/hooks/useFormJson.tsx
- src/hooks/useFormsConfig.tsx
- src/ohri-form.component.tsx
- src/utils/ohri-sidebar.ts
This PR makes various fixes and improvements. These include:
- Fixing a situation where date inputs with invalid content trap focus and prevent the user from clicking elsewhere on the page.
- Adds some padding around radio button inputs.
- Tweaks the appearance of the `Previous` value input - changing its label to read `Previous value` and adjusting elements in the UI.
- Rendering a loading spinner when the form is POSTing to the server.
- Render a warning modal when a user fills a form and then (inadvertently or otherwise) tries to navigate away from the page. This modal notifies the user that they might lose their changes by navigating away.
> (feat) Various tweaks and improvements

- __mocks__/forms/ohri-forms/filter-answer-options-test-form.json
- src/components/encounter/ohri-encounter-form.component.tsx
- src/components/group/ohri-obs-group.component.tsx
- src/components/inputs/multi-select/ohri-multi-select.component.tsx
- src/components/inputs/radio/ohri-radio.component.tsx
- src/components/inputs/select/ohri-dropdown.component.tsx
- src/components/inputs/unspecified/ohri-unspecified.component.tsx
- src/components/inputs/unspecified/ohri-unspecified.test.tsx
- src/components/section/ohri-form-section.component.tsx
- src/ohri-form.component.test.tsx
This PR adds skip logic to answer options i.e answer options in a drop down list, radio buttons or checkboxes can be hidden or shown based on answers in other questions.
Implementation:
```
"answers":[
{
"concept":"160036AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"label":"Transfer out",
"hide": {
"hideWhenExpression": "gravida > 2 && gravida <= 5"
}
},
{
"concept":"163266AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"label":"This facility",
"hide": {
"hideWhenExpression": "gravida > 5"
}
},
{
"concept":"52f7fc03-611b-4b62-8498-37beb2fa99ed",
"label":"In Transit",
"hide": {
"hideWhenExpression": "gravida > 5"
}
},
{
"concept":"54b96458-6585-4c4c-a5b1-b3ca7f1be351",
"label":"Missing"
}
]
```
The PR also fixes a minor bug of invoking the onChange function on a field whenever it's corresponding unspecified field is …
> add skip logic for answer options

- src/components/encounter/ohri-encounter-form.component.tsx
- src/components/inputs/date/ohri-date.component.tsx
- src/components/inputs/number/ohri-number.component.tsx
- src/components/inputs/radio/ohri-radio.component.tsx
- src/components/inputs/select/ohri-dropdown.component.tsx
- src/components/inputs/text/ohri-text.component.tsx
We introduced a feature to allow a user to select whether use of previous value should be enabled or not. This is both at field and form level using the usePreviousValueDisabled flag. However the moment the flag would be added, the use of previous value would be disabled irrespective of whether the flag is set to true or false.
This PR fixes that bug.
> fix usePreviousValueDisabled bug

- src/components/sidebar/ohri-form-sidebar.scss
- src/ohri-form.scss
Relates to [this conversation](https://openmrs.slack.com/archives/CHP5QAE5R/p1685109135001679) on Slack.
This PR removes some global styles from the form engine affecting the styling of the workspace window in the patient chart. It also applies some minor visual tweaks to the form engine, including:
- Tweaking the margin applied to the form pages on the sidebar on desktop
- Setting the form's height to the viewport's height so it spans the whole page.
- Setting the background colour of sidebar items on hover to `colors.$color-gray-10` (per this [design](https://zeroheight.com/23a080e38/p/9014c5-form-navigation)).
- Changing the background colour of the active form page in the sidebar to `colors.$color-gray-20` (per this [design](https://zeroheight.com/23a080e38/p/9014c5-form-navigation)). …
> (fix) Remove some global styles affecting the workspace

- src/utils/common-expression-helpers.ts
The problem with the function was that it directly modified the original date object using the setDate method. As a result, it caused unexpected behavior where the modification affected the original object. This led to the visit date and the next visit date being the same after adding a certain number of days to the visit date, as shown in the screenshot bellow:
To fix this issue, I created a new Date object based on the original date and perform the calculations on the new object.
Additionally, I included a check to verify if the resulting date is valid by checking if newDate.getTime() returns NaN. If the date is invalid, the function returns undefined and this was being displayed on the form.
> The addDaysToDate function should not modify the original date.

- src/components/inputs/date/ohri-date.component.tsx
- src/components/inputs/location/ohri-encounter-location.component.tsx
- src/components/inputs/multi-select/ohri-multi-select.component.tsx
- src/components/inputs/number/ohri-number.component.tsx
- src/components/inputs/radio/ohri-radio.component.tsx
- src/components/inputs/select/ohri-dropdown.component.tsx
- src/components/inputs/text-area/ohri-text-area.component.tsx
- src/components/inputs/text/ohri-text.component.tsx
- src/components/inputs/toggle/ohri-toggle.component.tsx
- src/components/inputs/ui-select-extended/ui-select-extended.tsx
In "edit" and "enter" mode, the fields marked as read-only should render the controlled in readOnly mode and not the default view mode display
Link to community ticket: https://issues.openmrs.org/browse/O3-2303
> fix/ O3-2253:Marking a field as readonly should render the field control as opposed to switching to view mode

- src/components/group/ohri-obs-group.component.tsx
Fix 'useField' being undefined for customly registered controls within obs groups.
> Fix 'useField' being undefined for customly registered controls within obs groups.

- src/api/api.ts
> (fix) Previous values should be picked from the latest encounter

- package.json
- src/utils/error-utils.ts
- yarn.lock
This PR changes the source of the `TFunction` type annotation for the i18next `t` function from 'react-i18next' to `i18next`. This is to fix an upstream issue in the Form Builder where upgrading react-i18next leads to a type error because the TFunction annotation cannot be found. Switching to importing the annotation from i18next [aligns](https://github.com/i18next/react-i18next/blob/1ff5cabcebcc833af8410dc4c69ea08070dda745/index.d.ts#L9) things nicely with the library. 
> Screengrab of the error from the form builder
> (fix) Import TFunction annotation from i18next

- src/components/encounter/ohri-encounter-form.component.tsx
- src/hooks/useFormFieldHandlers.tsx
- src/hooks/useInitialValues.ts
The FormFieldHandlers resolves all available handlers but was returning as undefined causing an error when opening a form view or edit action. Solution was to create a guard clause within the useEffect hook to check if is falsy and return an object thus preventing potential errors when trying to access properties of null or undefined.
> (fix) Cannot read properties of undefined obs when opening edit /view mode of a form

- src/components/warning-modal.component.tsx
- src/ohri-form.component.tsx
- This PR fixes the issue with the confirmation modal not closing the form upon clicking the "confirm" button. 
- This also fixes a follow up issue where the pop-up modal was showing even on view mode.
https://github.com/openmrs/openmrs-form-engine-lib/assets/51090527/9a1643b9-d37a-4896-a6ab-4b46bfc39235
> (fix) Allowing confirmation modal to close form / preventing pop up in view mode

- src/components/encounter/ohri-encounter-form.component.tsx
- src/hooks/usePostSubmissionAction.test.tsx
- src/ohri-form.component.tsx
- src/utils/error-utils.ts
> (fix) fix post submission action error, improve post submission error handling

- src/components/inputs/text/ohri-text.component.tsx
- src/components/inputs/unspecified/ohri-unspecified.component.tsx
- src/components/inputs/unspecified/ohri-unspecified.test.tsx
> (fix) fix ohri-unspecified issue

- __mocks__/forms/ohri-forms/obs-group-test_form.json
- src/api/types.ts
- src/components/encounter/ohri-encounter-form.component.tsx
- src/components/repeat/helpers.ts
- src/components/repeat/ohri-repeat.component.tsx
- src/hooks/useInitialValues.ts
- src/ohri-form.component.test.tsx
- src/utils/test-utils.ts
There was an error while editing an obs group field with more than one repeating groups. This was because at the point of initializing fields, the first(default) group wasn't being assigned a uuid.
SOme other fixes on how the repeat group ids are generated and unit tests.
N/A
> (fix) fix error editing obs group with more than one repeating group

- __mocks__/forms/ohri-forms/sample_fields.json
- src/api/types.ts
- src/components/group/ohri-obs-group.component.tsx
- src/components/group/ohri-obs-group.scss
- src/components/inputs/tooltip/ohri-tooltip.scss
- src/components/inputs/tooltip/ohri-tooltip.tsx
- src/components/section/ohri-form-section.component.tsx
- src/components/section/ohri-form-section.scss
- src/ohri-form.component.test.tsx
This PR adds support for rendering a tooltip which gives the user more information about a field within the React Form Engine.
> (feat) adding support for questionInfo

- __mocks__/forms/ohri-forms/labour_and_delivery_test_form.json
- src/api/types.ts
- src/components/encounter/ohri-encounter-form.component.tsx
- src/components/repeat/ohri-repeat.component.tsx
- src/hooks/useInitialValues.ts
- src/ohri-form-context.tsx
- src/ohri-form.component.test.tsx
- src/ohri-form.component.tsx
- src/submission-handlers/base-handlers.ts
- src/utils/ohri-form-helper.ts
This PR validates that the number of repeated obsGroup fields matches the repeat limit passed into the form's JSON
> (feat) obsGroup count validation

- __mocks__/forms/ohri-forms/labour_and_delivery_test_form.json
- __mocks__/forms/ohri-forms/post-submission-test-form.json
- src/api/api.ts
- src/api/types.ts
- src/components/inputs/ui-select-extended/ui-select-extended.test.tsx
- src/hooks/usePostSubmissionAction.tsx
- src/ohri-form.component.test.tsx
- src/ohri-form.component.tsx
- src/post-submission-actions/program-enrollment-action.ts
- src/registry/inbuilt-components/InbuiltPostSubmissionActions.ts
- src/registry/registry.ts
- src/utils/expression-parser.ts
- src/utils/post-submission-action-helper.ts
- src/utils/program-enrolment-helper.ts
This PR introduces generic program enrolment to the form engine. If an encounter is supposed to trigger a program enrolment, the user shall specify the same in the schema using `ProgramEnrollmentSubmissionAction` and specifying the program details through the config parameter. The user shall also use the enabled flag to specify whether the post submission is enabled or not. See sample below:
```
"postSubmissionActions": [
{
"actionId": "ProgramEnrollmentSubmissionAction",
"enabled":"tbProgramType === '160541AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'",
"config": {
"enrollmentDate": "tbRegDate",
"programUuid": "58005eb2-4560-4ada-b7bb-67a5cffa0a27",
"completionDate": "outcomeTBRx"
}
}
]
```
https://github.com/openmrs/openmrs-form-engine-lib/assets/12844964/073c4286-140e-45b2-afcc-5fe18e743ee4
> (feat) Introduce generic program enrollment

- src/components/inputs/ui-select-extended/ui-select-extended.test.tsx
- src/components/inputs/ui-select-extended/ui-select-extended.tsx
There was an issue where if a datasource had a config, the config would be loaded fine on page load but if there was any attempt to reload the component, the config value would disappear. This PR fixes the issue
> (fix) disappearance of config data on page reload

- src/post-submission-actions/program-enrollment-action.ts
We needed to check if the payload.dateEnrolled property is not already defined or is falsy, and assign the value of patientProgramEnrollment.dateEnrolled. This is needed so that using the `ProgramEnrollmentSubmissionAction` to add a client to a program works for a form without the `enrollmentDate` in the config obj
> (fix) refactor program enrollment action

- src/api/types.ts
- src/components/inputs/ui-select-extended/ui-select-extended.tsx
- src/datasources/concept-data-source.ts
- src/datasources/location-data-source.ts
The UI-select-extended control has 2 flavours:
`Preloaded`(default): Where the data source is loaded on page load and you just search through the items.
`Searchable`: Data source is not pre loaded but as you type, a request is made to the endpoint to return results matching the search criteria.
There were bugs for the `searchable` flavours, i.e in edit mode, it would not pick the saved value. Also in enter mode, it would not show the option for reusing previous value. 
This PR seeks to resolve the issues above
https://github.com/openmrs/openmrs-form-engine-lib/assets/12844964/5b855d7f-0bd6-42a1-9633-3cfd2fc89539
> fix UI-select-extended searchable issues

- src/components/section/ohri-form-section.component.tsx
Minor clean up of unnecessary import that was causing errors with linking
> (chore) removes unnecesary crypto import

- src/api/types.ts
- src/components/inputs/content-switcher/ohri-content-switcher.component.tsx
- src/components/inputs/date/ohri-date.component.tsx
- src/components/inputs/file/file.component.tsx
- src/components/inputs/location/ohri-encounter-location.component.tsx
- src/components/inputs/multi-select/ohri-multi-select.component.tsx
- src/components/inputs/number/ohri-number.component.tsx
- src/components/inputs/radio/ohri-radio.component.tsx
- src/components/inputs/select/ohri-dropdown.component.tsx
- src/components/inputs/text-area/ohri-text-area.component.tsx
- src/components/inputs/text/ohri-text.component.tsx
- src/components/inputs/toggle/ohri-toggle.component.tsx
- src/components/inputs/ui-select-extended/ui-select-extended.tsx
- src/components/label/ohri-label.component.tsx
- src/components/label/ohri-label.scss
- src/components/page/ohri-form-page.scss
- src/components/page/ohri-form-page.tsx
- src/components/section/ohri-form-section.component.tsx
- src/components/section/ohri-form-section.scss
- src/components/value/ohri-value.component.tsx
- src/components/value/ohri-value.scss
- src/components/value/view/ohri-field-value-view.component.tsx
- src/components/value/view/ohri-field-value-view.scss
- src/ohri-form.component.scss
- src/ohri-form.component.tsx
- src/utils/expression-runner.ts
- src/utils/ohri-form-helper.ts
This pull request introduces a new mode in the form engine, referred to as "embedded-view." This mode is designed to present a version of the view mode in a consolidated format, where question and answer pairs are rendered inline within a single file. This format eliminates the typical accordion structure. 
The introduction of this mode addresses the specific requirement of embedding the form engine within a widget to showcase form details in a report-like format. To activate this mode, users can pass the prop `mode='embedded-view'` to the `<OHRIForm />` component.
> (feat) Introducing widget-embedded view mode

- src/api/api.ts
- src/components/inputs/location/ohri-encounter-location.component.tsx
- src/components/section/helpers.ts
- src/registry/inbuilt-components/control-templates.ts
- src/registry/inbuilt-components/inbuiltControls.ts
The RFE was designed to pick encounter location based on the `rendering`. The AFE schemas however pick encounter location based on the `type`. This PR extends the component to understand both schemas.
https://github.com/openmrs/openmrs-form-engine-lib/assets/12844964/4ff9904f-f2d2-4e2d-aa59-cfbccaf869a3
> (feat) Extend encounter location to process AFE schema out of the box

- .eslintrc
- .husky/pre-commit
- .husky/pre-push
- package.json
- src/api/api.ts
- src/components/encounter/ohri-encounter-form.component.tsx
- src/hooks/useInitialValues.ts
- src/utils/expression-parser.ts
- src/utils/forms-loader.ts
- src/utils/post-submission-action-helper.ts
- yarn.lock
Our current setup is running Prettier as a part of ESLint. These are two separate concerns that should be handled separately by different tools.
This PR removes [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) and [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) from our linting config as recommended [here](https://prettier.io/docs/en/integrating-with-linters.html#notes) and [here](https://www.joshuakgoldberg.com/blog/you-probably-dont-need-eslint-config-prettier-or-eslint-plugin-prettier/). I've also separated ESLint concerns from Prettier so that ESLint doesn't handle both. The recommended modern approach treats Prettier and ESLint as separate unrelated tools.
I've also moved the `prettier` script from the root-level `package.json` …
> (chore) Separate linting and formatting concerns

- src/ohri-form.component.tsx
Add ability to hide the form-engine navigation column if only one page exists as shown in the GIF below.
https://www.loom.com/share/ca98349b95594e8993b71d97e4824ddf?sid=d7f48111-083f-4327-8d50-524dd4124d5e
https://openmrs.atlassian.net/browse/O3-2212
N/A
> (feat) Hide form side navigation for forms with only only page

- package.json
In this [commit](https://github.com/openmrs/openmrs-form-engine-lib/commit/0abc70543f12a814c1b167158ed8a9c4714ae4b4), I re-configured husky to be setup post-install. However, this seems to cause issues to node package managers while installing the form engine package:
```
yarn up @openmrs/openmrs-form-engine-lib@next
```
The above fails with an error:
```log
command not found: husky
```
> (chore) Attempt to fix "husky install" error encountered when installing this package in other npm packages

- src/components/section/helpers.ts
This fixes a bug on the form's engine that was breaking on previous value.
> (fix) bug fix for date previous-value display

- package.json
- prettier.config.js
This PR amends the glob patterns `lint-staged` considers when determining which staged files to run pre-commit tasks on. Also fixes a deprecated property in the Prettier config.
> (chore) Fix Prettier glob patterns

- src/components/inputs/markdown/markdown-wrapper.component.tsx
- src/components/inputs/markdown/ohri-markdown.component.tsx
- src/ohri-form.component.tsx
Here is the sample json markdown being used. The first part part shows the current implementation using array while the subsequent ones show changes in this PR with string as value and render to handle unsupported type
```json
{
"questions": [
{
"type": "markdown",
"rendering": "markdown"
},
"id": "fooMarkdown",
"value": [
"**This form is used to:** Document differentiated service deliver enrolment/ disenrolment.",
"\n\ntest 1",
"_test 3_"
]
},
{
"type": "markdown",
"rendering": "markdown"
},
"id": "fooMarkdown2",
"value": "**This form is used to:** \n\n Document _differentiated_ service deliver enrolment/ disenrolment."
},
{
"type": "markdown",
"rendering": "markdown"
},
"id": "fooMarkdown3",
"value": {
"wrongvalue": "wrong …
```
> O3-1990: Allow string as value for markdown

- src/api/api.ts
- src/api/types.ts
- src/components/encounter/ohri-encounter-form.component.tsx
- src/components/inputs/content-switcher/ohri-content-switcher.component.tsx
- src/components/inputs/date/ohri-date.component.tsx
- src/components/inputs/file/file.component.tsx
- src/components/inputs/location/ohri-encounter-location.component.tsx
- src/components/inputs/multi-select/ohri-multi-select.component.tsx
- src/components/inputs/number/ohri-number.component.tsx
- src/components/inputs/radio/ohri-radio.component.tsx
- src/components/inputs/select/ohri-dropdown.component.tsx
- src/components/inputs/text-area/ohri-text-area.component.tsx
- src/components/inputs/text/ohri-text.component.tsx
- src/components/inputs/toggle/ohri-toggle.component.tsx
- src/components/inputs/ui-select-extended/ui-select-extended.tsx
- src/ohri-form.component.test.tsx
- src/utils/ohri-form-helper.ts
- src/zscore-tests/bmi-age.test.tsx
- src/zscore-tests/height-age.test.tsx
- src/zscore-tests/weight-height.test.tsx
PR Adds the concept object  within the data structure (possible in a new "meta" property, so that we dont need to make subsequent backend calls to get more information about the concept associated with the question
> 03-2167:Support associating concept representation with questions

- src/components/inputs/date/ohri-date.component.tsx
- src/ohri-form.component.test.tsx
This PR looks into the following issues:
When a user selects a date, the date's equivalent in UTC is calculated and saved in the form. For the Timezones behind the UTC, when the user selects a date, the date's time is sent as `00:00:00` by the Date picker. Setting the date in the negative offset timezone would set the selected date as the previous one.
All the dates should be handled in local time zones
**For Pacific time zone**
https://github.com/openmrs/openmrs-form-engine-lib/assets/51502471/33f15f44-b0ee-4419-923d-43e611a17e63
https://issues.openmrs.org/browse/O3-2154
Also, the tests are updated such that they should work in all timezones
> (fix) O3-2154: Selecting a date should set selected date's time to midnight in the local timezone

- .github/workflows/ci.yml
- .github/workflows/size.yml
- package.json
- turbo.json
- yarn.lock
Bumps [turbo](https://github.com/vercel/turbo) to the latest available version, enabling the following improvements:
- https://turbo.build/blog/turbo-1-11-0
- https://turbo.build/blog/turbo-1-12-0
- https://turbo.build/blog/turbo-1-13-0
> (chore) Bump turbo

- src/ohri-form.component.tsx
Requirement for https://github.com/openmrs/openmrs-esm-patient-chart/pull/1804
None
https://issues.openmrs.org/browse/O3-3093
> (feat) Added new prop 'markFormAsDirty' in the ohri form

- package.json
- src/components/loaders/loading.component.tsx
- src/ohri-form.component.test.tsx
- src/utils/test-utils.ts
This PR refactors tests for the Form component with the primary goal of reducing reliance on async behaviour and the use of asynchronous matchers. Consequently, the test suite _should_ be easier to read and reason about. In most cases, rendering the component, allowing some time for the asynchronous behaviour to occur, and then checking for the disappearance of the loading spinner should be enough to allow asynchronous operations to complete. 
In the few cases where the delay is insufficient and more time is required for async operations to complete, I've queued up the render using:
```tsx
await act(async () => {
renderForm(null, obsGroupTestForm);
});
```
> (test) Refactor tests for the Form component

- src/components/section-collapsible-toggle/ohri-section-collapsible-toggle.scss
This PR fixes the vertical alignment of the toggle in the workspace header.
> (fix) Vertically align workspace header toggle

- src/components/inputs/date/ohri-date.component.tsx
- src/components/inputs/multi-select/ohri-multi-select.component.tsx
- src/components/inputs/number/ohri-number.component.tsx
- src/components/inputs/radio/ohri-radio.component.tsx
- src/components/inputs/select/ohri-dropdown.component.tsx
- src/components/inputs/text-area/ohri-text-area.component.tsx
- src/components/inputs/text/ohri-text.component.tsx
- src/components/inputs/ui-select-extended/ui-select-extended.component.tsx
- src/components/page/ohri-form-page.scss
This PR fixes the styling of required fields so that they get flagged better when a form is submitted without filling mandatory fields.
https://github.com/openmrs/openmrs-form-engine-lib/assets/8509731/c7d3d43f-c127-428c-8974-cb7cb746b314
> (fix) Flag required fields upon form submission

- src/components/encounter/ohri-encounter-form.component.tsx
- src/constants.ts
- src/hooks/useConcepts.tsx
- src/validators/default-value-validator.ts
This PR is dependent on https://github.com/openmrs/openmrs-form-engine-lib/pull/189 . It implements the aspect of supporting default answers for questions of concept Question incase answers for a question are not provided.
We consider supporting should render all the answer concepts associated with that concept in the concept dictionary as answer set
> (feat) 03 -2130: Add support of default answers for coded questions

- src/components/inputs/multi-select/multi-select.component.tsx
- src/components/inputs/multi-select/multi-select.scss
The React Form Engine fails to accurately translate UUIDs into their corresponding selected answers for multi-select responses. While in multi-select responses with the Angular Form Engine, selected answers typically display in the box as expected, the React Form Engine presents the UUID rather than the selected answer.
https://openmrs.atlassian.net/browse/O3-3099
> (feat) O3-3099: Render labels instead of UUIDs for multiCheckbox field answers

- package.json
- src/api/api.ts
- src/components/inputs/content-switcher/content-switcher.test.tsx
- src/components/inputs/location/encounter-location.component.tsx
- src/components/inputs/select/dropdown.test.tsx
- src/components/inputs/ui-select-extended/ui-select-extended.test.tsx
- src/components/inputs/unspecified/unspecified.test.tsx
- src/form-engine.component.tsx
- src/post-submission-actions/program-enrollment-action.ts
- src/submission-handlers/base-handlers.ts
- src/submission-handlers/encounterLocationHandler.ts
- yarn.lock
This PR fixes various TypeScript errors that arise when the library gets linked to the Patient Chart. These are owing to the following:
- A mismatch between the version of the `@types/react` package used in the chart versus the library. I've locked the version to a compatible release using the `resolutions` field of the manifest file.
- Some mismatching observable type annotations. I've replaced usages of `openmrsObservableFetch` with `openmrsFetch`, thereby avoiding the outdated types.
Next is to clear the errors when linking the Form Builder.
> (fix) Fix typescript errors shown when linking to Patient Chart

- src/components/sidebar/sidebar.scss
When you try to submit a form with validation errors, the affected pages are highlighted for visibility. Previously the styling was  broken, this fix addresses that issue.
https://openmrs.atlassian.net/browse/O3-3111
> (fix) O3-3111: Fix stylings in the side navigation

- src/api/api.ts
- src/form-engine.test.tsx
- src/hooks/useClobData.tsx
- src/hooks/useConcepts.tsx
- src/hooks/useEncounter.tsx
- src/hooks/useEncounterRole.tsx
- src/utils/common-utils.ts
- src/zscore-tests/bmi-age.test.tsx
- src/zscore-tests/height-age.test.tsx
- src/zscore-tests/weight-height.test.tsx
Updates `&_sort=` date param and updates to use `restBaseUrl` and `fhirBaseUrl`
> (fix) Updates sort params and switches to restBaseUrl

- src/utils/scroll-into-view.ts
Improve scrolling top most invalid field in to view when the form is in an invalid state
https://github.com/openmrs/openmrs-form-engine-lib/assets/53287480/70252dba-3fd8-4f4d-8039-f8eccefbce7b
[O3-3104](https://openmrs.atlassian.net/browse/O3-3104)
> (feat) O3-3104: Improve scrolling top most invalid field in to view when the form is in an invalid state

- src/components/inputs/date/date.component.tsx
- src/components/inputs/multi-select/multi-select-component.test.tsx
- src/components/inputs/multi-select/multi-select.component.tsx
- src/components/inputs/number/number.component.tsx
- src/components/inputs/radio/radio.component.tsx
- src/components/inputs/select/dropdown.component.tsx
- src/components/inputs/text-area/text-area.component.tsx
- src/components/inputs/text/text.component.tsx
- src/components/inputs/ui-select-extended/ui-select-extended.component.tsx
- src/components/required-field-label/required-field-label.component.tsx
- src/components/required-field-label/required-field-label.scss
- src/form-engine.test.tsx
- src/zscore-tests/bmi-age.test.tsx
- src/zscore-tests/height-age.test.tsx
- src/zscore-tests/weight-height.test.tsx
This PR adds a red asterisk to form labels for required fields as shown below:
https://github.com/openmrs/openmrs-form-engine-lib/assets/8509731/2cda3b00-520a-4c31-ad33-f3d2b0afb124
> (feat) Show asterisks next to labels for required fields

- src/form-engine.component.tsx
This PR hides the `save` and `cancel` buttons from the form's engine when the form is opened in `embedded-view` mode
> (fix) revise logic to show button set on embedded view mode

- package.json
- yarn.lock
`@carbon/react` had been switched to a dependency in a previous PR to reduce the bundle size but the catch is consuming esms might have varying versions which end up conflicting with it and causing UI issues like unintended scroll bars. 
This also raises an issue with `yarn link` that stalls the development process. 
**THIS MIGHT BE REVISITED LATER ON**
> (chore) Switch @carbon/react to peer dependency

- src/components/group/obs-group.component.tsx
- src/components/section/form-section.scss
There had been an issue reported where the general alignment of the tooltip within the form fields does not cascade to the obs group fields: (see image below)
This PR resolves this.
> (fix) fix tooltip alignment on obsGroup

- src/hooks/useConcepts.tsx
- src/utils/form-helper.ts
Currently, out of all concept references, only the top 50 references are fetched. With `useSWRInfinite` we can fetch all the concept references for the form in batches.
None
> (feat) Fetch all concept references of the the form with SWR Infinite

- src/components/encounter/encounter-form.component.tsx
- src/components/group/obs-group.component.tsx
- src/components/inputs/content-switcher/content-switcher.component.tsx
- src/components/inputs/content-switcher/content-switcher.test.tsx
- src/components/inputs/date/date.component.tsx
- src/components/inputs/multi-select/multi-select.component.tsx
- src/components/inputs/number/number.component.tsx
- src/components/inputs/radio/radio.component.tsx
- src/components/inputs/select/dropdown.component.tsx
- src/components/inputs/text-area/text-area.component.tsx
- src/components/inputs/text/text.component.tsx
- src/components/inputs/toggle/toggle.component.tsx
- src/components/inputs/tooltip/tooltip.component.tsx
- src/components/inputs/ui-select-extended/ui-select-extended.component.tsx
- src/components/inputs/unspecified/unspecified.component.tsx
- src/components/inputs/unspecified/unspecified.test.tsx
- src/components/label/label.component.tsx
- src/components/patient-banner/patient-banner.component.tsx
- src/components/previous-value-review/previous-value-review.component.tsx
- src/components/repeat/repeat.component.tsx
- src/components/section/form-section.component.tsx
- src/components/value/view/field-value-view.component.tsx
- src/form-engine.component.tsx
- src/registry/inbuilt-components/inbuiltControls.ts
- src/registry/registry.test.ts
We currently use a mix of named and default exports for components. This PR switches to using default exports for components with a single export, similar to what we do in other repositories. This makes things more consistent.
> (refactor) Use one component export syntax for consistency

- src/registry/inbuilt-components/inbuiltControls.ts
This fixes the issue related to rendering types: `encounter-provider`, `encounter-location`, `problem` and `drug` reported not working.
> (fix) Update registry to use `name` as the canonical identifier for derived rendering types

- __mocks__/patient.mock.ts
- src/zscore-tests/bmi-age.test.tsx
- src/zscore-tests/height-age.test.tsx
Changes in this PR fix a broken time sensitive test by making sure the internally referenced date is static as opposed to being a moving target. 
N/A
N/A
> (test) Fix broken "z-score" related unit test

- src/validators/default-value-validator.ts
The [default field validation](https://github.com/openmrs/openmrs-form-engine-lib/blob/40ec1b3fcd3132735fe8d8840aed851d3d1f740b/src/validators/default-value-validator.ts#L7-L14) is only looking at the scenario when the value is an array of one element , however for the case of the checkbox and multi-checbox the value will have more than one element ie  ['30e2da8f-34ca-4c93-94c8-d429f22d381c', '1e2918fb-4e15-11e4-8a57-0800271c1b75'] which causes Value not found in coded answers list error to be displayed as seen in the screenshot below yet both coded values are present in the answers coded list. We need to cater for multi-select fields to
> field-validation:Enabling default field validation for multi-checkbox field values 

- src/components/inputs/multi-select/multi-select.component.tsx
This aims to fix an issue with the multi-select component where it doesn't preselect previously selected values while in edit mode. 
https://www.loom.com/share/6a7b2ac48ff7430ba25e6a75da42c1d3
https://openmrs.atlassian.net/browse/O3-3135
> (fix) Multi-select component to initialise and display consistently in edit mode

- src/utils/patient-identifier-helper.ts
This PR is addressing the issue whereby after saving a form of patient identifier type, upon subsequent attempts to reload the form in the form-renderer the schema fails to load.
https://www.loom.com/share/7d5e92a9e98c423cb05270701f7539cb
> (fix) Fix conditional access check affecting patientIdentifier type fields 

- src/components/encounter/encounter-form.component.tsx
- src/hooks/useEncounter.tsx
Switches useEncounter from `useSWR` to `openmrsFecth`. Whereas this had some performance benefits, it’s at the cost of loading stale data. renamed the hook from `useEncounter` to `getEncounter`
https://github.com/openmrs/openmrs-form-engine-lib/assets/15266028/925e23ac-da5a-49e7-a6fd-f64152ebb363
https://openmrs.atlassian.net/browse/O3-3164
> (fix) O3-3164 switch to openmrsFetch to fetch encounter

- .gitignore
- .vscode/settings.json
- src/components/encounter/encounter-form-manager.ts
- src/components/encounter/encounter-form.component.tsx
- src/components/repeat/repeat.component.tsx
- src/registry/registry.ts
This PR aims at ensuring that empty repeat fields are hidden.
Issue:
Solved:
N/A
> (feat) Hide empty repeating groups

- src/components/group/obs-group.component.tsx
- src/components/section/form-section.scss
https://openmrs.atlassian.net/browse/O3-3126
> (fix) 03-3126 : Aligning field width within an an obs-group

- package.json
- src/form-engine.component.tsx
- yarn.lock
Bumps the @types/react and formik versions to the latest available releases. Bumping @types/react means we don't have to rely on [selective dependency resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) and we can use the same version of it everywhere this library is used. Bumping [formik](https://github.com/jaredpalmer/formik/releases/tag/formik%402.4.6) fixes issues with outdated type annotations. This PR should be merged with related PRs in Form Builder and Patient Chart.
This PR also adds a `typescript` script to the manifest file that runs the typescript compiler to check types.
> (chore) Bump @types/react and formik

- src/components/inputs/date/date.component.tsx
- src/components/loaders/loader.scss
- src/components/sidebar/sidebar.component.tsx
- src/components/sidebar/sidebar.scss
- src/form-engine.component.tsx
- src/form-engine.scss
This PR applies various fixes to the form engine UI, including:
- Fixing the form layout in the tablet viewport
- Making several tweaks to align with the available designs [here](https://zpl.io/JEkGxlr) and [here](https://zeroheight.com/23a080e38/p/9014c5-form-navigation). 
https://openmrs.atlassian.net/browse/O3-3252
> (feat) Form engine UI improvements

- src/form-engine.component.tsx
- src/post-submission-actions/program-enrollment-action.ts
- src/transformers/angular-fe-schema-transformer.ts
- src/types.ts
- This pr adds on to the program enrollments AFE : RFE parity by adding a function in the transformer to convert program meta tags to post submission handlers and creates/updates exisiting enrollments
- 
https://github.com/openmrs/openmrs-form-engine-lib/assets/19533785/26874e7d-a1b5-402a-a3d0-72c1c7031bd7
https://openmrs.atlassian.net/browse/O3-3239
> (feat) O3-3239 Add support for program enrollments using meta tag

- __mocks__/forms/afe-forms/afe-schema-trasformer-form.json
- src/components/encounter/encounter-form-manager.ts
- src/components/encounter/encounter-form.component.tsx
- src/components/inputs/content-switcher/content-switcher.test.tsx
- src/components/inputs/select/dropdown.test.tsx
- src/components/inputs/text/text.test.tsx
- src/components/inputs/ui-select-extended/ui-select-extended.test.tsx
- src/components/inputs/unspecified/unspecified.test.tsx
- src/datasources/encounter-role-datasource.ts
- src/form-context.tsx
- src/form-engine.component.tsx
- src/hooks/useInitialValues.test.ts
- src/hooks/useInitialValues.ts
- src/registry/inbuilt-components/control-templates.ts
- src/registry/inbuilt-components/inbuiltDataSources.ts
- src/registry/inbuilt-components/inbuiltFieldSubmissionHandlers.ts
- src/registry/inbuilt-components/template-component-map.ts
- src/submission-handlers/encounterRoleHandler.ts
- src/submission-handlers/obsHandler.test.ts
- src/submission-handlers/patietnIdentifierHandler.test.ts
- src/submission-handlers/testOrderHandler.test.ts
- src/transformers/angular-fe-schema-transformer.test.ts
- src/transformers/angular-fe-schema-transformer.ts
- src/types.ts
- This PR adds support for choosing an encounter role, if a form has an `encounterRole` question, the selected role overrides the default `Clinian` role.
- Recording
https://github.com/openmrs/openmrs-form-engine-lib/assets/30952856/4af72116-f03b-46be-aef9-f9abe6223598
- https://openmrs.atlassian.net/browse/O3-3162
> (feat) Support for an capturing encounter role.

- src/components/encounter/encounter-form.component.tsx
- src/components/inputs/content-switcher/content-switcher.component.tsx
- src/components/inputs/date/date.component.tsx
- src/components/inputs/multi-select/multi-select-component.test.tsx
- src/components/inputs/multi-select/multi-select.component.tsx
- src/components/inputs/number/number.component.tsx
- src/components/inputs/radio/radio.component.tsx
- src/components/inputs/select/dropdown.component.tsx
- src/components/inputs/text-area/text-area.component.tsx
- src/components/inputs/text/text.component.tsx
- src/components/inputs/text/text.test.tsx
- src/components/inputs/toggle/toggle.component.tsx
- src/components/inputs/ui-select-extended/ui-select-extended.component.tsx
- src/components/inputs/unspecified/unspecified.component.tsx
- src/components/repeat/helpers.ts
- src/form-context.tsx
- src/registry/inbuilt-components/inbuiltFieldSubmissionHandlers.ts
- src/submission-handlers/inlineDateHandler.ts
- src/transformers/angular-fe-schema-transformer.ts
- src/types.ts
- src/utils/expression-runner.ts
- src/utils/form-helper.ts
- This PR implements the conditional appending of an inline date picker to a question when `showDate: true` is defined in the parent question. The value of this date field is then submitted as the `obsDatetime` for that question.
- The PR also handles some validations on the date picker which are passed to the `showDateOptions` object.
- Example
```
{
"name": "Hadijah Test form",
"pages": [
{
"label": "page 1",
"sections": [
{
"label": "Section one",
"isExpanded": "true",
"questions": [
{
"label": "Height",
"type": "obs",
"required": false,
"id": "height",
"rendering": "number",
"concept": "5090AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"showDate": "true",
"showDateOptions": {
"validators": [
{
"type": "date",
"allowFutureDates": "false"
}
]
},
"conceptMappings": [
{ …
```
> (feat) Implement the inline date picker with showDate and shownDateOptions

- src/components/inputs/ui-select-extended/ui-select-extended.component.tsx
- src/datasources/concept-set-members-data-source.ts
- src/datasources/select-concept-answers-datasource.ts
- src/hooks/useDatasourceDependentValue.ts
- src/registry/inbuilt-components/inbuiltDataSources.ts
Within AFE, the functionality for `select-concept-answers` is that the datasource is configured make a network request using the field's `conceptUuid`. However, in the event that an answer is selected within an associated field, the datasource will make a network request based on the uuid tied to the answer selected in the associated field, thus giving a different list in the dropdown with every different answer selected.
This PR adds this functionality, enabling the dropdown to be populated based on a the answer selected in a referenced field.
It also enables `select-concept-answers`'s list of answers to be populated by data from a `Coded` concept. 
Sample schema: 
```json
{
"name": "Test select concept answers",
"pages": [
{
"label": "page one",
"sections": [
{
"label": "First Section", …
```
> (refactor) O3-3297: Refactor select concept answers

- src/form-engine.component.tsx
- src/utils/expression-runner.ts
This PR introduces a fix for failing expressions within the forms' engine.
https://openmrs.atlassian.net/jira/software/c/projects/O3/boards/37?assignee=712020:381d2aac-e89b-44ab-803b-02445824ad47&selectedIssue=O3-3274
> (fix) O3-3274: Fix failing expressions

- src/components/inputs/content-switcher/content-switcher.component.tsx
- src/components/inputs/date/date.component.tsx
- src/components/inputs/multi-select/multi-select.component.tsx
- src/components/inputs/number/number.component.tsx
- src/components/inputs/radio/radio.component.tsx
- src/components/inputs/select/dropdown.component.tsx
- src/components/inputs/text-area/text-area.component.tsx
- src/components/inputs/text/text.component.tsx
- src/components/inputs/ui-select-extended/ui-select-extended.component.tsx
- src/components/section/form-section.component.tsx
- src/types.ts
This PR moves the extraction of the value from the previous value object to happen from the section component, such that only the value is passed down to the input control and not the entire object
https://openmrs.atlassian.net/browse/O3-3338
> (fix)03-3338 :Refactor extraction of previous value to the section component.

- __mocks__/forms/rfe-forms/conditional-answered-form.json
- src/components/encounter/encounter-form.component.tsx
- src/form-engine.test.tsx
- src/hooks/useFieldValidationResults.ts
- src/registry/inbuilt-components/inbuiltValidators.ts
- src/types.ts
- src/utils/form-helper.ts
- src/validators/conditional-answered-validator.ts
This PR aims to introduce conditional answered validation to the form's engine.
https://github.com/openmrs/openmrs-form-engine-lib/assets/51090527/ab086194-db2c-40f3-88ec-dc96e29f7b7c
https://openmrs.atlassian.net/browse/O3-3061
> (feat) O3-3061: Support for conditional answered validation

- src/submission-handlers/encounterProviderHandler.test.ts
Adding test coverage for the encounter provider handler for handlingFieldSubmission, getting initial and previous values
> (test) Adding test coverage for the encounter provider handler

- src/submission-handlers/encounterRolesHandler.test.ts
Adding test coverage for the encounter role handler for handlingFieldSubmission, getting initial and prevoius values
> (test) Adding test coverage for the encounter role handler

- src/components/encounter/encounter-form.component.tsx
- src/form-engine.component.tsx
- src/hooks/useEncounterRole.tsx
PR is enabling the loading of encounter roles from the encounter-form component 
https://openmrs.atlassian.net/browse/O3-3321
> (refactor)03-3321: Move encounter role(s) logic to the encounter-form component

- src/components/inputs/multi-select/multi-select.component.tsx
- src/components/inputs/multi-select/multi-select.scss
This PR aims at fixing a few minor issues related to https://github.com/openmrs/openmrs-form-engine-lib/pull/232. It basically:
1. Ensures that a required field's label is highlighted using an asterisk
2. Ensures that the field label is styled conventionally  
Before:
After:
> (fix) Consistently style multi-select field labels

- src/components/inputs/content-switcher/content-switcher.component.tsx
- src/components/inputs/date/date.component.tsx
- src/components/inputs/number/number.component.tsx
- src/components/inputs/radio/radio.component.tsx
- src/components/inputs/select/dropdown.component.tsx
- src/components/inputs/text-area/text-area.component.tsx
- src/components/inputs/text/text.component.tsx
- src/components/inputs/ui-select-extended/ui-select-extended.component.tsx
This PR is removing the redundant `value` state coming from the `previous value` across all components in the engine
> (refactor) Remove redundant "value" state derived from the "previous value"

- src/transformers/default-schema-transformer.ts
This PR modifies the schema transformer to only update encounter-date fields with the "ui-select-extended" rendering. This change prevents unintended modifications to other field instances. 
N/A
N/A
N/A
> (fix) Restrict schema transformer mutations to 'ui-select-extended' rendering on encounter-date fields

- src/components/inputs/file/file.component.tsx
This PR resolves the issue where the UI throws an error when trying to initialize an attachment field with an empty attachment value in edit mode.
https://openmrs.atlassian.net/browse/O3-3377
> (fix) O3-3377: error on bootstrapping attachment field on edit mode 

- src/components/inputs/select/dropdown.component.tsx
This PR addresses a performance issue with the Dropdown component. When launching a Clinical form in the tablet viewport and clicking on a dropdown field, the Dropdown component re-renders excessively, causing the entire form UI to freeze. To mitigate this, I've updated the useEffect hook's dependency array and cached the `handleChange` function definition to ensure stability between re-renders. I need to investigate further to understand the root cause, although these two measures seem to resolve the bug.
https://github.com/openmrs/openmrs-form-engine-lib/assets/8509731/50f55cee-f2c3-449f-b3db-ff4708e9ac8
https://github.com/openmrs/openmrs-form-engine-lib/assets/8509731/82aa0ed5-442a-42d9-a66c-89f7ed09cb0c
[O3-3350](https://openmrs.atlassian.net/issues/O3-3350)
We should enable the …
> (fix) O3-3350: Resolve dropdown re-rendering bug in the tablet viewport

- src/form-engine.test.tsx
- src/hooks/useConcepts.tsx
- src/hooks/useRestMaxResultsCount.ts
- src/hooks/useSystemSetting.ts
- src/utils/form-helper.ts
The count of concepts in a form can exceed the maximum results returned by the REST module. Hence, we use the global property `webservices.rest.maxResultsCount` system setting, defining the maximum results count the REST module can deliver in a single result.
Hence we create the chunks of UUIDs in the size of the value returned by the above mentioned system settings and fetch the results accordingly.
This PR reverts the change made in **form-helper** in #241. 
For the URLs where the response is not mocked, the `openmrsFetch` returns `undefined` in the tests, which when read by `useSWRInfinite` maps the response to `[ undefined ]`, which then breaks the function written in the form-helper (link mentioned above).
```
Error: Cannot read `uuid` of undefined
```
None
None
> (fix) O3-2168: Concept reference chunk size depends on REST `webservices.rest.maxResultsCount` property

- src/components/encounter/encounter-form.component.tsx
- src/components/page/form-page.component.tsx
- src/hooks/useFormCollapse.tsx
- src/types.ts
- src/utils/form-page-utils.ts
This PR fixes the issue with forms not collapsing/expanding after configuring the `isExpanded` property within the schema.
https://github.com/openmrs/openmrs-form-engine-lib/assets/51090527/86db74f6-443b-4600-a797-93fc57c8b98a
https://openmrs.atlassian.net/browse/O3-3378
> (fix) O3-3378: Revise logic for expanding and collapsing a section

- src/components/inputs/date/date.component.tsx
- src/components/inputs/date/date.scss
- src/components/inputs/unspecified/unspecified.test.tsx
- src/form-engine.test.tsx
- src/submission-handlers/obsHandler.test.ts
- src/submission-handlers/obsHandler.ts
- src/transformers/default-schema-transformer.ts
- src/types.ts
This PR aims to support the rendering of a time picker alongside the date picker based on the prop `datePickerFormat`. If the prop is null, only the date picker will be displayed.
**Submitting values**
https://github.com/openmrs/openmrs-form-engine-lib/assets/34070216/6d9f844b-3b3b-4574-ac9e-d3af8fa29cc5
**Editing time**
https://github.com/openmrs/openmrs-form-engine-lib/assets/34070216/f17c41cb-7523-41d2-baab-3a0ce9030776
[JIRA ticket](https://issues.openmrs.org/browse/O3-2491)
[PR to update prop name](https://github.com/openmrs/openmrs-esm-form-builder/pull/290)
> (feat) O3-2491: Add support for a time picker

- src/form-engine.scss
PR addresses styling of single-page forms in a maximized workspace ie content to be aligned at the top
https://www.loom.com/share/6635a174b3044555b0a8463f17475aa3
https://openmrs.atlassian.net/browse/O3-3407
> (fix)03:3407 Fix styling of single-page forms in a maximized workspace

- src/components/group/obs-group.component.tsx
- src/components/repeat/repeat.component.tsx
- src/components/section/form-section.component.tsx
This PR ensures that FieldComponent instances are properly identified and managed by React, preventing potential rendering issues. Specifically, it addresses a recently reported issue where ui-select-ext instances were rendering incorrectly and switching data sources.
Issue:
https://github.com/openmrs/openmrs-form-engine-lib/assets/26084581/e0d3e1ba-23bf-402a-a06c-cfb7177a5b4d
Fixed:
> (fix) Add unique key prop to field component instances

- package.json
- src/components/inputs/select/dropdown.component.tsx
- yarn.lock
This PR fixes an issue with the dropdown component re-rendering infinitely on selecting an option in tablet view port. This issue [stems from the "downshift"](https://github.com/downshift-js/downshift/issues/1511) library consumed by Carbon and it seems to be affecting React v18. It was since resolved [in downshift](https://github.com/downshift-js/downshift/pull/1558) `v8.2.4` and [carbon](https://github.com/carbon-design-system/carbon/pull/15454). 
I've also changed Carbon from a peer dependency to a normal dependency.
https://issues.openmrs.org/browse/O3-3350
> (fix) O3-3350: Resolve infinite re-rendering of the dropdown component in the tablet viewport

- src/components/inputs/multi-select/multi-select.component.tsx
- src/types.ts
Switches from constraining inline display of multi-select from number of answers to using config.  Previously the limit was less than 5 answers but with this users have the choice to dictate their preference. This requirement also matches behavior from other engines.  
**Sample Usage** 
Add `inlineMultiCheckbox` key to your already existing multi-checkbox fields
```
{
"label": "Sample Section",
"isExpanded": "true",
"questions": [
{
"label": "Inline multi-checkbox",
"type": "obs",
"required": false,
"id": "anotherSampleQuestion",
"rendering": "multiCheckbox",
"concept": "xxxx",
"answers": [...]
},
"inlineMultiCheckbox": true
}
]
}
```
https://github.com/openmrs/openmrs-form-engine-lib/assets/15266028/9c5f9e9a-a7c4-41c4-bc24-d8880a5a6b91 …
> (feat) O3-3481 Adds option to display multi-checkbox inline

- src/hooks/useConcepts.tsx
- Use chunks of `100` for the concept references so as to avoid the URI exceeding the limit.
NB: The system default chunkSize works as data limit but in this case it was failing because it was being used to determine the number of concept uuids to be added to the url and this is what caused the limit bug.
So in this case, we don't need the system default chunk size (1000) because that would me 1000 concept uuids added to the endpoint as query params. 
In this PR, I used a random value `100` which is efficient in performance of the request time and a good chunk to fetch in cases where we have a lot of data.
- 
- No ticket
> (Fix) Use size 100 for the references chunk size to append to the url.

- src/components/encounter/encounter-form.component.tsx
This PR introduces support for answers belonging to fields with `coded` type renderings to disable whenever you select an answer within the same field. 
https://github.com/openmrs/openmrs-form-engine-lib/assets/51090527/77b2f30d-d09c-4f1d-8b00-a5e16ce19095
https://openmrs.atlassian.net/browse/O3-3444
> (feat) O3-3444 - Disable an answer within a question referencing an answer within that same question

- src/form-engine.component.tsx
This PR introduces functionality that disables the save buttons while form dependencies are loading. 
https://github.com/openmrs/openmrs-form-engine-lib/assets/51090527/d34831ad-dcc4-4c0f-ae54-db4c04bf34bc
> (fix) O3-3417: Disable save button while loading form dependencies

- src/validators/conditional-answered-validator.test.ts
> (test):Conditional answered validator test coverage

- __mocks__/use-initial-values/encounter.mock.json
- src/hooks/useInitialValues.test.ts
- src/hooks/useInitialValues.ts
… values
This PR resolves the issue of null or undefined initial values for calculated fields when entering edit mode. Previously, the assumption was that all calculated fields would be retrieved through asynchronous functions from the expression runner. This assumption led to problems when synchronous functions were used, resulting in null or undefined initial values.
https://www.loom.com/share/866edea9d4c34b91ab4ef3ef93eba49c?sid=7ffa7c0d-58cd-42e2-a30f-64d4448462d7
> (fix) O3-2252: Calculated values shouldn't be overwritten by the Encounter's values

- src/utils/expression-parser.test.ts
- src/utils/expression-parser.ts
- src/utils/expression-runner.ts
This PR introduces a fix for various failing expression evaluations due to improper formatting during form construction.
https://openmrs.atlassian.net/browse/O3-3337
> (fix) O3-3337 - Support expressions that don't use whitespace as delimiters

- src/components/page/form-page.scss
UI was breaking when a form section would be collapsed and expanded again.
https://github.com/openmrs/openmrs-form-engine-lib/assets/12844964/a8c5d282-661d-4b4b-80bc-1461f578a947
https://openmrs.atlassian.net/issues/O3-3532
> (fix) O3-3532: Fix broken UI on collapsing and reopening form sections

- src/utils/form-helper.test.ts
PR is adding test coverage for some form helper functions
> (test):Adding some test coverage for form-helper functions

- src/utils/expression-parser.test.ts
- src/utils/expression-parser.ts
- src/utils/expression-runner.ts
Reverts openmrs/openmrs-form-engine-lib#327
> Revert "(fix) O3-3337 - Support expressions that don't use whitespace as delimiters"

- src/api/api.ts
When fetching a form by name, the current form engine returns a list of forms with that name, including retired forms. Using the o3 forms endpoint, it is possible that the returned result might be a retired form. This PR ensures that the latest (most recent) form is fetched instead of the first item in the array, which could be a retired form.
> (fix) Update form fetch request to return the latest form by uuid or name

- src/utils/common-expression-helpers.ts
This PR corrects the gravida calculation logic within the form engine.
> (fix) Reworked logic for gravida calculation

- src/components/inputs/date/date.component.tsx
- src/components/inputs/unspecified/unspecified.test.tsx
- src/form-engine.test.tsx
- yarn.lock
The onChange function sends in the date as a single value of type `CalendarDate`. In our local date change handler, we were converting this date to a Javascript date with the line: 
`const refinedDate = date instanceof Date ? new Date(date.setHours(0, 0, 0, 0)) : new Date(date);`
This ideally should cause a typescript error saying that `Date` does not accept type `CalendarDate` as a param.
But, due to the way that we passed in the onChange handler to the `OpenmrsDatePicker` and the way that we had defined the local date handler, typescript didn't pick it up and a Javascript date was created without any error.
How we passed in our function to the `onChange` parameter:
`onChange={ (date) => onDateChange( [date] ) }` 
Local date handler's function definition:
`const onDateChange = ( [date] ) …
> (fix) Update onDateChange function

- src/components/inputs/date/date.component.tsx
The time picker should display the question's label if it is not rendered along with the calendar. Before the fix, the time picker would just render the text 'Time' as the label.
https://issues.openmrs.org/browse/O3-3673
> (fix): Timepicker should have question label

- src/components/inputs/ui-select-extended/ui-select-extended.component.tsx
Updated UiSelectExtended component to properly clear the selected item in the ComboBox when the value is set to null.
- Added useEffect to listen for changes to field.value and reset the ComboBox selection and search term when field.value is null.
- Ensured Formik's internal state is also updated by using helpers.setValue(null, false).
https://github.com/user-attachments/assets/b8ddd5a3-5d8e-4372-9096-f2b6467208f8
> (Fix) Ensure clearing slection for ui-extended-select

- __mocks__/session.mock.ts
- src/components/inputs/date/date.component.tsx
- src/components/inputs/multi-select/multi-select.test.tsx
- src/components/inputs/unspecified/unspecified.test.tsx
- src/components/section/form-section.component.tsx
- src/form-engine.test.tsx
- src/zscore-tests/bmi-age.test.tsx
- src/zscore-tests/height-age.test.tsx
- src/zscore-tests/weight-height.test.tsx
- yarn.lock
Related to https://github.com/openmrs/openmrs-esm-patient-management/pull/1264.
This PR fixes failing assertions by removing partial mocks that extend the framework mock. We shouldn't need to extend the framework mock this way as it already provides most of the stubs one would need to mock out in a test. I couldn't get the `FormEngine` component tests to pass and couldn't figure out why. Any help figuring that out would be much appreciated. We'd need to get this PR in and then bump the library in Patient Chart as a prerequisite to fixing the same issue in Patient Chart. So this PR is a blocker in that sense.
> (test) Fix failing tests by removing partial framework mocks

- .github/workflows/ci.yml
- README.md
- package.json
- src/globals.ts
- yarn.lock
> (BREAKING): Rename form engine to @openmrs/esm-form-engine-lib

- src/provider/form-factory-provider.tsx
- translations/en.json
Currently when submitting a form successfully, the message “A new encounter was created“ is displayed. This PR changes the success message to a better success message that says “Form submitted successfully“.
https://issues.openmrs.org/browse/O3-3743
> (fix) O3-3743: Better success message when submitting a form.

- src/components/renderer/form/form-renderer.component.tsx
- src/form-engine.component.tsx
- src/provider/form-factory-provider.tsx
- yarn.lock
The workspace system exposes an API that prevents forms with draft data or unpersisted data from being closed accidentally, which could lead to data loss. This functionality was supported by the form engine prior to the migration; this PR restores that support in the form engine.
> (feat) Implement 'markFormAsDirty' to prompt the user before closing a dirty form

- src/form-engine.component.tsx
This PR addresses an issue with the patient banner not working as expected. The root cause was identified as the `<Form>` component from the Carbon Design System, which does not support ref forwarding. This caused the ref to remain null.
https://openmrs.atlassian.net/browse/O3-3740
> (fix) Fix patient banner

- src/components/inputs/number/number.component.tsx
The value from the NumberInput field was being captured as a string. As a result, the form-validator would return false when checking if the value is an integer. 
Before fix:
https://github.com/user-attachments/assets/8ba2341a-ac9b-48ea-8932-6dec56cec057
After fix:
https://github.com/user-attachments/assets/9244109b-2e4c-4a4f-b1e1-11baeb172d1f
> (fix) parse NumberInput value to Number

- src/provider/form-factory-provider.tsx
Added a check to the `registerForm` function to verify if the incoming form is not already set as the root form.
N/A
https://openmrs.atlassian.net/browse/O3-3882
> (fix) Resolve duplicate form registration

- src/components/inputs/date/date.component.tsx
- src/components/inputs/number/number.component.tsx
- src/components/inputs/text/text.component.tsx
This adds condition to hide number input if the hide expression is true. Currently the hideExpression doesn't work for number fields and those fields are always rendered. This fixes that. 
**Before**
Number fields are always rendered regardless of expression logic
**Expected Behavior**
Number fields with hide expression logic should be hidden by default and only visible when expression condition is true
> (fix) Add hide expression condition for number fields

- src/components/group/obs-group.component.tsx
- src/components/inputs/select/dropdown.component.tsx
- src/components/renderer/field/form-field-renderer.component.tsx
- src/components/renderer/section/section-renderer.component.tsx
- src/components/repeat/repeat.component.tsx
- src/hooks/useFormStateHelpers.ts
**Background:** In the form-engine, state management is typically handled using a reducer pattern, often in conjunction with React's useReducer hook. This is propped with helpers to conveniently update the state eg. [updateFormField](https://github.com/openmrs/openmrs-esm-form-engine-lib/blob/main/src/hooks/useFormStateHelpers.ts#L9-L11). 
**Issue:** The form-renderer currently [receives the field object directly from the section](https://github.com/openmrs/openmrs-esm-form-engine-lib/blob/main/src/components/renderer/section/section-renderer.component.tsx#L15) instead of the reactive flattened form fields state. This obscures the cascade of the reactive events.
**Solution**: Treat the flattened `formFields` state as the source of truth.
N/A
https://openmrs.atlassian.net/browse/O3-3908
> (fix) Reactively cascade form field update event

- src/components/inputs/workspace-launcher/workspace-launcher.component.tsx
This adds condition to hide the workplace launcher button if the hide expression is true. Currently the hideExpression doesn't work for workplace launcher fields. This fixes that.
https://github.com/user-attachments/assets/32b05ca6-8730-41fd-b608-c2726397f6d2
https://openmrs.atlassian.net/browse/O3-3910
> (fix) Add hide expression condition for workplace-launcher

- src/components/renderer/field/form-field-renderer.component.tsx
- src/registry/registry.ts
- src/utils/form-helper.ts
Moving the getFieldControlWithFallback(..) function to the registry resolves most of the issues related to cyclic refs.
> (chore) Move getFieldControlWithFallback to registry 

- __mocks__/forms/rfe-forms/conditional-required-form.json
- __mocks__/forms/rfe-forms/labour_and_delivery_test_form.json
- __mocks__/forms/rfe-forms/radio-button-form.json
- jest.config.js
- src/components/inputs/radio/radio.component.tsx
- src/components/inputs/radio/radio.test.tsx
- src/components/inputs/select/dropdown.component.tsx
- src/components/inputs/unspecified/unspecified.component.tsx
- src/components/label/label.component.tsx
- src/components/processor-factory/form-processor-factory.component.tsx
- src/components/renderer/custom-hooks-renderer.component.tsx
- src/components/renderer/field/form-field-renderer.component.tsx
- src/form-engine.component.tsx
- src/form-engine.test.tsx
- src/hooks/useFormStateHelpers.ts
- src/hooks/useInitialValues.ts
- src/hooks/useProcessorDependencies.ts
- src/processors/encounter/encounter-form-processor.ts
- src/provider/form-factory-helper.ts
- src/registry/registry.ts
- src/utils/form-helper.ts
Enables the form-engine component test suite by fixing the broken tests.
N/A
https://openmrs.atlassian.net/browse/O3-3922
> (chore) O3-3922: Enable form-engine component test suite 

- src/adapters/obs-adapter.test.ts
- src/adapters/obs-adapter.ts
- src/components/inputs/date/date.component.tsx
- src/form-engine.component.tsx
- src/utils/common-utils.ts
For some reason the workspace no longer provides the "session mode" details to the root component. As result, we end up with an `undefined` "session mode" value which causes side effects like the "use previous value" feature not working. This PR ensures we infer the session mode in such scenarios. It the obs adapter to ensure that we properly format the date object to a display string.
https://openmrs.atlassian.net/browse/O3-3918
> (fix) Resolve issue with loading previous values

- src/api/index.ts
- src/hooks/useFormJson.test.tsx
- src/hooks/useFormJson.tsx
Enhances the form loader to throw an error that is then reported to user incase the queried form resource was not found.
N/A
> (fix) Throw error when queried form is not found

- __mocks__/forms/rfe-forms/multi-select-form.json
- src/components/inputs/multi-select/multi-select.component.tsx
- src/components/inputs/multi-select/multi-select.test.tsx
- src/form-engine.test.tsx
- src/transformers/default-schema-transformer.test.ts
- src/transformers/default-schema-transformer.ts
- src/types/schema.ts
- src/utils/test-utils.ts
This pull request aims to enhance the rendering options for checkboxes by supporting two distinct types: `checkbox` and `checkbox-searchable`.
- **Rendering Types:** 
- The `checkbox` type will render the conventional checkbox group.
- The `checkbox-searchable` type will render a compact version (combo-box)
- **Backward Compatibility:** 
- To maintain backward compatibility, the `multiCheckbox` property will default to the `checkbox-searchable` rendering type. If the `inlineMultiCheckbox` property is present and set to `true`, it will be mapped to the checkbox rendering type
Checkbox rendering:
Checkbox searchable:
`multiCheckbox`:
`multiCheckbox` with `inlineMultiCheckbox` set to `true`
https://openmrs.atlassian.net/browse/O3-3831
> (feat) Enhance support for "checkbox" rendering

- src/components/processor-factory/form-processor-factory.component.tsx
- src/components/renderer/form/form-renderer.component.tsx
- src/form-engine.component.tsx
- src/provider/form-factory-provider.tsx
During initialization, the form renderer registers the associated form context with the form-factory provider, which can be either a root form or a subform. This context is stored as an object reference in memory. As the user interacts with the form, the context undergoes mutations as a side-effect. In most cases, these mutations do not cause issues because they occur at deeper levels within the object tree, and most state updates perform shallow clones. However, problems arise when state mutations happen at higher levels, such as with the `formFields` state.
This has caused to a bug with repeating fields, where newly cloned fields do not exist in the factory provider during submission.
---
This fix ensures that state updates are properly propagated, addressing the issue and maintaining …
> (fix) Propagate Form Context State Changes to the Form Factory Provider

- src/components/inputs/number/number.component.tsx
- src/components/inputs/number/number.test.tsx
Carbon's `NumberInput` misbehaves when passed a `NaN` value. This PR addresses this issue by resolving NaN values.
**Bug in action**:  
_(The number input fails to render because the calculate expression returns a NaN.)_
**Fixed**:
N/A
> (fix) Resolve a bug where a NaN value causes an infinite re-render cycle in the Number input

- src/components/inputs/date/date.component.tsx
- src/components/inputs/date/date.test.tsx
- src/processors/encounter/encounter-form-processor.ts
- src/types/schema.ts
This PR ensures that the form engine evaluates calculate expressions after the general form field initialization. This ensures that any referenced fields (in the calculate expression) are initialised prior.  
Before:
Applying any logic would default it to 1970 because of the null value
After:
> (fix) Evaluate calculate expressions after general form field initialization

- __mocks__/forms/rfe-forms/sample_unspecified-form.json
- src/components/inputs/unspecified/unspecified.component.tsx
- src/components/inputs/unspecified/unspecified.test.tsx
- src/components/renderer/field/form-field-renderer.component.tsx
- src/utils/common-utils.ts
Fixes a couple bugs and adds tests coverage around the support of unspecified fields.
https://openmrs.atlassian.net/browse/O3-4064
> (fix) O3-4064 - Enhance Support for Marking Fields as Unspecified

- jest.config.js
- src/utils/form-helper.test.ts
This PR adds a `clearMocks` option to the Jest config to automatically [clear mocks](https://jestjs.io/docs/configuration#clearmocks-boolean) between tests. With this, you don't need to manually clear mocks in beforeEach blocks.
> (test) Auto-clear jest mocks

- src/components/renderer/form/form-renderer.component.tsx
- src/components/renderer/page/page.renderer.component.tsx
- src/components/renderer/page/page.renderer.scss
- src/form-engine.component.tsx
- src/provider/form-factory-provider.tsx
This PR primarily restores the ability to collapse and expand all visible form pages and sections.
**Out of scope**:
1. **Unmounting Issue**: This PR resolves an issue where toggling between expanding and collapsing a page caused its child sections to unmount from the DOM. This was addressed by removing the conditional rendering of sections within the PageRenderer.
2. **UI Enhancements**: Additionally, this PR introduces UI tweaks that visually nest sections within their respective page containers. 
**Unmounting Issue:**
_(The Encounter Provider and Location fields are remounted)_
**Unmounting Issue Fixed:**
**Other features:**
N/A
Note: Carbon doesn't support nesting accordions, which is why I resorted to manipulating the visibility of the sections during page collapse; see:
- …
> (feat) Restore ability to collapse and expand the entire form

- src/processors/encounter/encounter-form-processor.ts
This fix resolves an issue where initial values from calculateExpressions weren't being persisted. This was mostly because the expressions are promises and the values were being set before the promise is resolved.
> (fix) Await for async calculate expressions to resolve at initialisation

- __mocks__/forms/rfe-forms/read-only-validation-form.json
- __mocks__/packages/hiv/forms/hts_poc/1.1.json
- src/form-engine.test.tsx
- src/utils/forms-loader.test.ts
O3-3937 Add test coverage around form readonly mode
https://openmrs.atlassian.net/browse/O3-3937
> (test) O3-3937 Add test coverage around form readonly mode

- src/components/inputs/date/date.component.tsx
- src/components/label/label.scss
The Openmrs datepicker doesn't currently support native readonly mode, this changes so that the date field renders same as view mode when readonly is `true`
> (fix) Render date readonly same as view mode

- __mocks__/forms/rfe-forms/js-expression-validation-form.json
- src/form-engine.test.tsx
- src/provider/form-factory-helper.ts
- src/validators/js-expression-validator.test.ts
- src/validators/js-expression-validator.ts
This PR fixes the JavaScript expression-based validator by ensuring that formFields are correctly set in the validator's context.
Issue:
Fixed:
> (fix) Resolve Error in JavaScript Expression Validation

- src/components/renderer/field/fieldLogic.ts
- src/components/renderer/field/form-field-renderer.component.tsx
- src/form-engine.test.tsx
This PR fixes an issue where calculated values aren't correctly prepared for submission. These changes ensure that the calculated value is validated and transformed into an OpenMRS object. 
N/A
> (fix) Validate and transform calculated value(s)

- src/components/repeat/repeat.component.tsx
This PR fixes an issue where deleted form fields (deleted cloned fields) re-appear on form submission. The issue is fixed by removing the deleted field(s) from the form context.
Issue:
[Screencast from 20-11-24 16_54_58.webm](https://github.com/user-attachments/assets/b8d4073c-e2f9-4325-9b96-8d042d2ffb6f)
> (fix) Remove deleted field from the form context

- src/adapters/obs-adapter.ts
- src/components/renderer/field/fieldLogic.ts
- src/components/renderer/field/form-field-renderer.component.tsx
- src/processors/encounter/encounter-form-processor.ts
Makes extraction of calculated value null safe in scenarios where return value differs
> (fix) Make extraction of the calculated value null safe

- src/adapters/obs-adapter.test.ts
- src/components/group/obs-group.component.tsx
- src/components/group/obs-group.scss
- src/components/renderer/field/form-field-renderer.component.tsx
- src/components/repeat/repeat.component.tsx
- src/hooks/useFormFields.ts
- src/processors/encounter/encounter-form-processor.ts
- src/processors/encounter/encounter-processor-helper.ts
- src/transformers/default-schema-transformer.ts
This PR introduces functionality for handling nested obsGroup questions. With this enhancement, users can now nest obsGroup elements within other obsGroup elements, allowing for complex hierarchical structures within forms. This feature supports scenarios requiring parent-child relationships among grouped observations, providing a more flexible and detailed data-capture process.
Example schema
```typescript
{
"name": "Test Nested obsGroup",
"pages": [
{
"label": "Test Nested obsGroup",
"sections": [
{
"label": "Test Nested obsGroup",
"isExpanded": "true",
"questions": [
{
"label": "Parent obsGroup",
"type": "obsGroup",
"required": false,
"id": "parentObsgroup",
"rendering": "group",
"concept": "163770AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
},
"questions": [
{
"label": "Health …
```
> (feat) O3-4137: Add support for nested obsGroup 

- src/components/inputs/text/text.component.tsx
- src/components/inputs/text/text.test.tsx
- src/components/renderer/field/form-field-renderer.component.tsx
- src/components/renderer/form/form-renderer.component.tsx
- src/components/repeat/helpers.ts
- src/components/repeat/repeat.component.tsx
- src/hooks/useFormStateHelpers.ts
This PR fixes an issue where cloned fields skip logic doesn't work as expected within obs group instances. The issue has been fixed by including all form fields (including the freshly cloned fields) in the expression runner's context. 
Issue:
https://github.com/user-attachments/assets/4b35b0f9-45af-4ff0-b6d8-54bd302d7445
Fixed:
https://openmrs.atlassian.net/browse/O3-4157
> (fix) Properly sanitize and initialize cloned fields

- src/adapters/obs-adapter.ts
- src/api/index.ts
- src/types/domain.ts
- src/utils/form-helper.test.ts
- src/utils/form-helper.ts
The obs value extractor currently supports Obs in the OpenMRS data modeling; This PR adds support for FHIR obs.
https://openmrs.atlassian.net/browse/O3-4220
> (fix) Historical value extractor should support FHIR obs

- src/components/renderer/field/fieldLogic.ts
- src/hooks/useEvaluateFormFieldExpressions.ts
- src/utils/form-helper.ts
The visibility cascading logic for form fields was not correctly updating the modified field within the form's context. This could lead to inconsistent state management and potential UI/data synchronization issues. The issue has been resolved by updating the form field in the context.
> (fix) Form Context Field Visibility Not Updating Correctly

- src/components/renderer/field/form-field-renderer.component.tsx
- src/form-engine.test.tsx
- Added logic to update an obs group’s state whenever a group member’s state changes.
- This ensures consistency in forms with flattened fields by keeping the group in sync with its members.
> (fix) Update obs group state when a group member changes

- src/utils/common-expression-helpers.test.ts
- src/utils/common-expression-helpers.ts
Tweaks the logic of the `calcMonthsOnART` expression helper function to use dayjs for more accurate month calculation. Presently, it only calculates months if at least 30 days have passed since the ART start date. It does so by calculating the difference in days between today and the ART start date, and then dividing by 30.
This PR changes the logic to use dayjs to calculate the difference in months between today and the ART start date. The motivation for this change is to fix a failing test on the main branch that arose from the previous logic.
@samuelmale could you advise on an appropriate test plan for this change?
> (refactor) Tweak calcMonthsOnART helper logic

- src/components/sidebar/sidebar.component.tsx
- src/components/sidebar/sidebar.scss
- src/form-engine.component.tsx
- src/form-engine.scss
Fixes an issue with the submit button not being disabled when the form is being submitted. Also tweaks the inline loading indicator shown in the button so that it doesn't take up extra vertical space.
> (fix) Fix submit button loading state

- src/components/inputs/date/date.component.tsx
Removes an unnecessary closing parenthesis in the date field's time validation regex pattern.
> (fix) Correct regex pattern for 12-hour time validation

- __mocks__/forms/rfe-forms/obs-group-test_form.json
- src/components/group/obs-group.component.tsx
- src/form-engine.test.tsx
This PR fixes an issue observed in the "Adult HIV Return Visit Form" where labels are floating around without corresponding input controls. 
This issue specifically affects groups without visible members in the initial render stage. The solution is treating the flattened forms fields state from the context as the source of truth.
> (fix) Hide empty obs groups

- src/components/inputs/ui-select-extended/ui-select-extended.component.tsx
- src/hooks/useEncounter.ts
- src/hooks/useFormJson.ts
- src/hooks/usePatientPrograms.ts
- src/hooks/useProcessorDependencies.ts
This PR fixes potential memory leaks by preventing state updates on unmounted components. It does so by adding cleanup functions to useEffect hook that fetch data. Per the [React docs](https://react.dev/learn/synchronizing-with-effects#fetching-data), if your effect fetches some data, the cleanup function should either abort the fetch or ignore its result. 
This PR adds abort controller signals to effects that directly leverage `openmrsFetch` and implements the [ignore flag pattern](https://react.dev/learn/synchronizing-with-effects#fetching-data) for custom promises (like loadDependencies) that don't directly use `openmrsFetch`.
Big caveat - I've not actually tested that this code works without breaking anything.
> (fix) Prevent state updates on unmounted components

- package.json
- yarn.lock
Cuts a new patch release of React Form Engine, `v3.0.1` with backwards compatible bug fixes and improvements to testing and documentation.
Here's the draft changelog:
* (fix) Fix submit button loading state by @denniskigen in https://github.com/openmrs/openmrs-esm-form-engine-lib/pull/439
* (fix) Tweak `calcMonthsOnART` helper logic by @denniskigen in https://github.com/openmrs/openmrs-esm-form-engine-lib/pull/441
* (fix) Translate answer labels by @samuelmale in https://github.com/openmrs/openmrs-esm-form-engine-lib/pull/443
* (fix) Hide empty obs groups by @samuelmale in https://github.com/openmrs/openmrs-esm-form-engine-lib/pull/444
* (fix) Clean up hooks by @denniskigen in https://github.com/openmrs/openmrs-esm-form-engine-lib/pull/445
* (fix) Prevent state updates on unmounted …
> (chore) Release v3.0.1

- src/hooks/usePatientPrograms.ts
- src/processors/encounter/encounter-form-processor.ts
- src/types/domain.ts
Refactors the usePatientProgram hook to leverage an SWR hook for fetching patient programs. With this, we get:
- Automatic caching and revalidation
- Conditional fetching based on the patientUuid and the `formJson.meta.programs.hasProgramFields` property of the form
- Built-in error and loading states
- Better handling of race conditions
What's a good test plan for this, @samuelmale? I've tweaked @CynthiaKamau's sample schema from [this PR](https://github.com/openmrs/openmrs-esm-form-engine-lib/pull/273) and amended to include a truthy `meta.programs.hasProgramFields` value to get the hook to run. I get active enrollments back as evidenced by the console.log in this screenshot:
Is there a more thorough way to test this?
> (refactor) Refactor usePatientPrograms hook to use SWR

- src/components/inputs/ui-select-extended/ui-select-extended.component.tsx
- src/components/inputs/ui-select-extended/ui-select-extended.test.tsx
- Updated shouldFilterItem to always return true, ensuring all items are displayed when the caret is clicked.
- Adjusted tests to validate that all items remain visible even after typing input.
https://github.com/user-attachments/assets/85e7989e-39fc-44df-9876-0f7bfd686a2d
https://openmrs.atlassian.net/browse/O3-3911
> (feat) O3-3911 Display all items on ui-select-extended

- src/adapters/obs-adapter.test.ts
- src/adapters/program-state-adapter.test.ts
- src/components/renderer/form/form-renderer.component.tsx
- src/components/renderer/form/state.ts
- src/components/repeat/repeat.component.tsx
- src/hooks/useFormStateHelpers.ts
- src/processors/encounter/encounter-processor-helper.ts
- src/provider/form-provider.tsx
Add ability to track deleted fields in repeat component, this is helpful in instances where the fields need to be voided. currently, the removed fields are not part of the context.
> (feat) Add ability to track deleted fields in repeat component

- src/components/inputs/multi-select/multi-select.component.tsx
Fixes an issue where tooltips for non-required (optional) multi-select field instances don't work as expected. 
https://openmrs.atlassian.net/browse/O3-3881
> (fix) O3-3881: Render tooltips for optional multi-select fields

- src/components/inputs/file/file.scss
- src/components/renderer/page/page.renderer.scss
- src/components/sidebar/sidebar.component.tsx
- src/components/sidebar/sidebar.scss
- src/form-engine.component.tsx
The forms workspace should be rendered in a `wider` [workspace size](https://github.com/openmrs/openmrs-esm-core/blob/f8f53c0a13696cebcab34d0f5311819d6d6ec46f/packages/framework/esm-extensions/src/workspaces.ts#L50). The following changes are made so that the form renders in a proper manner.
1. The sidebar should be hidden for `narrow` workspace size
2. The sidebar links and buttons should have a `sm` size for desktop view
3. The file uploader buttons expand through the form space. The buttons should wrap accordingly.
4. The accordion by default has a `padding-right` of 2.5rem, which takes up the space necessary for rendering form content.
https://github.com/user-attachments/assets/18ab2468-ced9-45a4-b3ee-3d1df5359b7b
https://openmrs.atlassian.net/browse/O3-4410
> (fix) O3-4410: Adjust Form Workspace Size & Enhance Form UI

- .github/workflows/ci.yml
Pre-release version number has been using the current release version numbers which didn't make sense especially because pre-release should point to the next possible version.
Previously:
New:
> (chore) Makes pre-release version numbers incremental

- __mocks__/forms/rfe-forms/mockSaveEncounter.json
- package.json
- src/form-engine.test.tsx
- yarn.lock
Upgrade to @carbon/react 1.73.0
https://openmrs.atlassian.net/jira/software/c/projects/O3/issues/O3-3540?jql=project%20%3D%20%22O3%22%20AND%20assignee%20%3D%20empty%20ORDER%20BY%20created%20DESC
> (chore) O3-3540: Bump @carbon/react to v1.74.0

- src/hooks/useFormJson.ts
- src/post-submission-actions/program-enrollment-action.ts
- src/processors/encounter/encounter-form-processor.ts
Replace occurrences of form-engine-lib namespace in favor of form-engine-app to handle form translations
> (fix) Switches to form-engine-app namespace for form translations

- src/components/sidebar/sidebar.scss
This PR addresses ticket O3-4474, which highlights an issue where the Cancel button in the React Form Engine sidebar uses a red hover background. The button should follow the Carbon Button component's tertiary variant styling and display the default hover color defined by $button-tertiary-hover.
Changes include:
- Removing the custom hover style that forces a red background on the Cancel button.
- Allowing the default Carbon hover behavior to apply, which resolves the color inconsistency.
https://github.com/user-attachments/assets/c3d971f1-decc-4515-99e2-bb302edca6c8
https://openmrs.atlassian.net/browse/O3-4474
> (fix) O3-4474: Form "Cancel" button shouldn't have a red background on hover

- src/datasources/select-concept-answers-datasource.ts
Replaces string literal replacement with proper URL parameter interpolation for `conceptUuid`. This fixes [an issue](https://openmrs.slack.com/archives/C02UNMKFH8V/p1741477460891589) where forms fail to render correctly in edit mode due to improper URL parameter handling. The previous implementation caused concept data to be fetched incorrectly.
Before:
https://github.com/user-attachments/assets/35b1ac4b-e235-4fc1-bca0-d806e546b4d5
After:
https://github.com/user-attachments/assets/2228a75f-a266-4b05-b933-61bca42f50ea
> (fix) Consistently interpolate `conceptUuid` URL parameter in `SelectConceptAnswersDatasource`

- package.json
- src/post-submission-actions/program-enrollment-action.ts
- src/processors/encounter/encounter-form-processor.ts
The processor files have multiple `showSnackbar` calls with translation strings, but these are not extracted by the `i18next-parser`. The i18next parser looks for `t(key, defaultValue, options)`pattern, and our `translateFrom` function can be modified in the following manner to match the i18next parser format.
```
const t = (key, value, options) => translateFrom(moduleName, key, value, options)
```
Before the parser extracted only 39 keys.
Now, the parser extracts 59 keys (addition of 20 keys)
None
> (feat) Extract translations from processor files

- src/components/group/obs-group.component.tsx
- src/components/renderer/field/form-field-renderer.component.tsx
- Added error handling to prevent app from becoming unresponsive when an obsGroup child shares the same ID as its parent.
- Stop multiple recursion which makes form-builder app stop responding.
- Displays a meaningful error message in Preview.
Before:
[Screencast from 2025-03-19 11-39-37.webm](https://github.com/user-attachments/assets/c887136d-5152-4930-98f1-21f80fcd6341)
After:
[Screencast from 2025-03-19 19-20-06.webm](https://github.com/user-attachments/assets/4e170388-5f5a-4766-8d7f-5c11a58e2312)
https://openmrs.atlassian.net/browse/O3-4546
> (fix) O3-4546 Prevent form from freezing when an obsGroup child has the same ID as its parent by displaying an error message.

- src/components/inputs/number/number.component.tsx
This PR fixes setting the Number Input's value. It uses the second argument of Carbon's `NumberInput`, which returns the updated value, including the changes made by the controls.
https://github.com/user-attachments/assets/19f3afb0-e625-4fc5-9e88-315351d66b63
None
> (fix) Use the correct value arg for the Number Input

- src/components/inputs/markdown/markdown.component.tsx
- src/components/inputs/multi-select/multi-select.component.tsx
Adds missing translation wrapper to markdown value and selected answers on multi-select fields
**Before:**
Markdown:
Multi-select answers:
**After:**
Markdown:
Multi-select answers:
> (fix) Add translation wrapper to markdown and multi-select answers

- package.json
- src/components/inputs/select/dropdown.component.tsx
- src/form-engine.test.tsx
- yarn.lock
Bumps @carbon/react to `^v1.76.0`, aligning the dependency version with the version we're pointing to in Core and everywhere else. Additionally, this adds an aria-label to the dropdown component to ensure that it remains accessible in tests using accessibility roles.
Everything should continue to work
> (chore) Bump @carbon/react and core OpenMRS dependencies

- src/components/inputs/number/number.component.tsx
The Carbon Input by default restricts the value change by the steppers between min and max values. But this restriction isn't working for the form engine. I went to the [Carbon NumberInput code for the min and max restriction](https://github.com/carbon-design-system/carbon/blob/0ce91ed5ad791ce04fa7878f2d3cffe7496267c3/packages/react/src/components/NumberInput/NumberInput.tsx#L376) and realized that the min and max value we might be sending is actually `undefined`, and if any value among the min/max values is `undefined`, the restriction doesn't work.
I went to the code and realized that the final value for the min and max `value` is: `Number(field.questionOptions.min) || undefined`. Now, if the `field.questionOptions.min = 0`, the value passed isn't 0, but `undefined`. The `||` check must …
> (fix) Undefined `min` and `max` values for the number inputs

- src/components/field-label/field-label.component.tsx
- src/form-engine.test.tsx
The field label tooltip wasn't being displayed so this PR removes extra wrapper that was initially added.
**BEFORE**
Tooltip wouldn't display on hover
**AFTER**
> (fix) Remove unnecessary extra wrapper from field label

- src/processors/encounter/encounter-processor-helper.ts
This PR updates the encounter submission logic to ensure `encounter.encounterDatetime` is initialized by the backend unless the form explicitly defines a field bound to `encounter.encounterDatetime`.
See related fix for the AFE: https://github.com/openmrs/openmrs-ngx-formentry/pull/131
> (fix) Initialize encounter date on backend if not defined within form fields

- src/components/renderer/field/fieldRenderUtils.test.ts
- src/components/renderer/field/fieldRenderUtils.ts
- src/components/renderer/field/form-field-renderer.component.tsx
- src/form-engine.test.tsx
- src/hooks/useEvaluateFormFieldExpressions.ts
Use the `hideUnansweredQuestionsInReadonlyForms` config flag to hide unanswered questions in read‑only O3 forms (embedded view), unless an explicit hide expression is defined.
https://github.com/openmrs/openmrs-esm-patient-chart/pull/2693
https://openmrs.atlassian.net/browse/O3-4959
> (feat) O3-4959: Support hiding unanswered questions in embedded forms via config

- src/components/renderer/field/form-field-renderer.component.tsx
This PR adds a try-catch block around the external module configuration retrieval to prevent the component from crashing when the configuration from `@openmrs/esm-form-engine-app` module cannot be loaded. This is needed for cases where like the form-builder where the `@openmrs/esm-form-engine-app` is not used.  The component now gracefully falls back to a default value (false) for hideUnansweredQuestionsInReadonlyForms and logs a warning when configuration loading fails.
After:
https://github.com/user-attachments/assets/cafbf652-df19-4b95-919c-3c190d7a6a3d
Before:
https://github.com/user-attachments/assets/41a07bbc-7df4-4dc9-b067-b7f1b1c45012
> (fix): Add fallback for hideUnansweredQuestionsInReadonlyForms config
